const ELENCOS = {

  "Argélia": {
    GK:  ["MASTIL", "BENBOT", "ZIDANE"],
    DEF: ["MANDI", "ABADA", "TOUGAI", "BELAID", "HADJAM", "AIT NOURI", "BELGHALI", "BENSEBAINI", "CHERGUI"],
    MID: ["ZERROUKI", "AOUAR", "CHAIBI", "BOUDAOUI", "BENTALEB", "MAZA", "TITRAOUI"],
    FWD: ["MAHREZ", "GOUIRI", "HADJ MOUSSA", "BENBOUALI", "AMOURA", "BOULBINA", "GHEDJEMIS"],
  },

  "Argentina": {
    GK:  ["MUSSO", "RULLI", "E. MARTINEZ"],
    DEF: ["SENESI", "TAGLIAFICO", "MONTIEL", "MARTINEZ", "ROMERO", "OTAMENDI", "MEDINA", "MOLINA"],
    MID: ["PAREDES", "DE PAUL", "BARCO", "LO CELSO", "PALACIOS", "N. GONZALEZ", "MAC ALLISTER", "E. FERNANDEZ"],
    FWD: ["J ALVAREZ", "MESSI", "ALMADA", "SIMEONE", "NICO PAZ", "LOPEZ", "L. MARTINEZ"],
  },

  "Austrália": {
    GK:  ["RYAN", "IZZO", "BEACH"],
    DEF: ["DEGENEK", "CIRCATI", "ITALIANO", "BOS", "GERIA", "TREWIN", "BEHICH", "SOUTTAR", "BURGESS", "HERRINGTON"],
    MID: ["METCALFE", "O'NEILL", "DEVLIN", "IRVINE", "OKON-ENGSTLER"],
    FWD: ["LECKIE", "TOURE", "HRUSTIC", "MABIL", "IRANKUNDA", "VOLPATO", "VELUPILLAY", "YENGI"],
  },

  "Áustria": {
    GK:  ["SCHLAGER", "WIEGELE", "PENTZ"],
    DEF: ["AFFENGRUBER", "DANSO", "POSCH", "ALABA", "LIENHART", "MWENE", "FRIEDL", "SVOBODA"],
    MID: ["XAVER", "SEIWALD", "SABITZER", "GRILLITSCH", "CHUKWUEMEKA", "SCHMID", "LJUBICIC", "LAIMER", "PRASS", "WANNER", "SCHÖPF"],
    FWD: ["ARNAUTOVIC", "GREGORITSCH", "KALAJDZIC", "WIMMER"],
  },

  "Bélgica": {
    GK:  ["COURTOIS", "LAMMENS", "PENDERS"],
    DEF: ["DEBAST", "THEATE", "MECHELE", "DE CUYPER", "MEUNIER", "DE WINTER", "SEYS", "CASTAGNE", "NGOY"],
    MID: ["WITSEL", "DE BRUYNE", "TIELEMANS", "MOREIRA JR", "VANAKEN", "SAELEMAEKERS", "RASKIN", "ONANA"],
    FWD: ["LUKAKU", "TROSSARD", "DOKU", "LUKEBAKIO", "DE KETELAERE", "FERNANDEZ-PARDO"],
  },

  "Bósnia e Herzegovina": {
    GK:  ["VASILJ", "JURKAS", "ZLOMISLIĆ"],
    DEF: ["MUJAKIĆ", "HADŽIKADUNIĆ", "MUHAREMOVIĆ", "KOLAŠINAC", "DEDIĆ", "KATIĆ", "RADELJIĆ", "MALIĆ"],
    MID: ["TAHIROVIĆ", "GIGOVIĆ", "BAŠIĆ", "SUNJIĆ", "MEMIĆ", "HADŽIAHMETOVIĆ", "BURNIĆ", "MAHMIĆ"],
    FWD: ["BAZDAR", "DEMIROVIĆ", "DŽEKO", "ALAJBEGOVIĆ", "BAJRAKTAREVIĆ", "TABAKOVIĆ", "LUKIĆ"],
  },

  "Brasil": {
    GK:  ["A. BECKER", "WEVERTON", "EDERSON"],
    DEF: ["GABRIEL", "MARQUINHOS", "ALEX SANDRO", "DANILO", "BREMER", "LÉO PEREIRA", "DOUGLAS S.", "IBAÑEZ"],
    MID: ["EDERSON S.", "CASEMIRO", "BRUNO G.", "FABINHO", "DANILO S.", "L. PAQUETÁ"],
    FWD: ["VINI JR.", "CUNHA", "NEYMAR JR", "RAPHINHA", "ENDRICK", "L. HENRIQUE", "MARTINELLI", "THIAGO", "RAYAN"],
  },

  "Cabo Verde": {
    GK:  ["VOZINHA", "MÁRCIO", "DOS SANTOS"],
    DEF: ["STOPIRA", "BORGES", "LOPES", "COSTA", "LOPES CABRAL", "MOREIRA", "WAGNER P.", "KELVIN"],
    MID: ["KEVIN L.", "JOVANE", "JOÃO PAULO", "MONTEIRO", "RODRIGUES", "D. DUARTE", "L. DUARTE", "Y. SEMEDO", "SEMEDO", "ARCANJO", "DA COSTA", "HÉLIO"],
    FWD: ["BENCHIMOL", "LIVRAMENTO", "RYAN"],
  },

  "Canadá": {
    GK:  ["ST. CLAIR", "CRÉPEAU", "GOODMAN"],
    DEF: ["JOHNSTON", "JONES", "DE FOUGEROLLES", "WATERMAN", "CORNELIUS", "BOMBITO", "DAVIES", "LARYEA", "SIGUR"],
    MID: ["CHOINIÈRE", "EUSTÁQUIO", "KONÉ", "MILLAR", "SHAFFELBURG", "OSORIO", "SALIBA"],
    FWD: ["LARIN", "J. DAVID", "OLUWASEYI", "BUCHANAN", "AHMED", "PROMISE", "NELSON"],
  },

  "Colômbia": {
    GK:  ["OSPINA", "C. VARGAS", "MONTERO"],
    DEF: ["D. MUÑOZ", "J. LUCUMÍ", "ARIAS", "Y. MINA", "PUERTA", "J. MOJICA", "W. DITTA", "MACHADO", "SÁNCHEZ"],
    MID: ["K. CASTAÑO", "RICHARD RÍOS", "CARRASCAL", "JAMES", "J. ARIAS", "PORTILLA", "J. LERMA", "QUINTERO"],
    FWD: ["LUIS DÍAZ", "CÓRDOBA", "C. HERNÁNDEZ", "CAMPAZ", "SUÁREZ", "A. GÓMEZ"],
  },

  "RD Congo": {
    GK:  ["MPASI", "FAYULU", "EPOLO"],
    DEF: ["WAN BISSAKA", "KAPUADI", "TUANZEBE", "BATUBINSIKA", "J. KAYEMBE", "MBEMBA", "KALULU", "MASUAKU"],
    MID: ["MUKAU", "MBUKU", "MOUTOUSSAMY", "BONGONDA", "SADIKI", "TSHIBOLA", "PICKEL", "E. KAYEMBE"],
    FWD: ["CIPENGA", "KAKUTA", "MESCHACK", "BAKAMBU", "MAYELE", "WISSA", "BANZA"],
  },

  "Costa do Marfim": {
    GK:  ["Y. FOFANA", "KONE", "LAFONT"],
    DEF: ["O. DIOMANDE", "G. KONAN", "SINGO", "KOSSOUNOU", "OPERI", "G. DOUE", "AGBADOU", "NDICKA"],
    MID: ["SERI", "FOFANA", "KESSIE", "SANGARE", "GUIAGON", "INAO"],
    FWD: ["BONNY", "ADINGRA", "YAN DIOMANDE", "WAHI", "DIAKITE", "AMAD", "PEPE", "GUESSAND", "TOURE"],
  },

  "Croácia": {
    GK:  ["LIVAKOVIĆ", "PANDUR", "KOTARSKI"],
    DEF: ["STANIŠIĆ", "PONGRAČIĆ", "GVARDIOL", "ĆALETA-CAR", "ŠUTALO", "JAKIĆ", "VUŠKOVIĆ", "ERLIĆ"],
    MID: ["MORO", "KOVAČIĆ", "MODRIĆ", "VLAŠIĆ", "PAŠALIĆ", "BATURINA", "P. SUČIĆ", "FRUK", "SUČIĆ"],
    FWD: ["KRAMARIĆ", "BUDIMIR", "PERIŠIĆ", "MATANOVIĆ", "M. PAŠALIĆ", "MUSA"],
  },

  "Equador": {
    GK:  ["GALÍNDEZ", "RAMÍREZ", "VALLE"],
    DEF: ["TORRES", "HINCAPIE", "ORDÓÑEZ", "PACHO", "ESTUPIÑÁN", "PRECIADO", "POROZO", "MEDINA"],
    MID: ["ALCÍVAR", "A. VALENCIA", "KENDRY", "MINDA", "VITE", "CASTILLO", "FRANCO", "M. CAICEDO"],
    FWD: ["YEBOAH ZAMORA", "RODRÍGUEZ", "E. VALENCIA", "J. CAICEDO", "PLATA", "ANGULO", "ARÉVALO"],
  },

  "Egito": {
    GK:  ["M. ELSHENAWY", "M. SOLIMAN", "SHOUBIR", "M. ALAA"],
    DEF: ["YASSER", "M. HANY", "HOSSAM", "R. RABIA", "M. ABDELMONIEM", "A. FATOUH", "K. HAFEZ", "T. ALAA"],
    MID: ["E. ASHOUR", "ZICO", "H. FATHY", "M. LASHIN", "DONGA", "M. ATTIA", "M. SABER"],
    FWD: ["M. TREZEGUET", "ABDELKARIM", "M. SALAH", "H. HASSAN", "I. ADEL", "MARMOUSH", "ZIZO"],
  },

  "Inglaterra": {
    GK:  ["PICKFORD", "D. HENDERSON", "TRAFFORD"],
    DEF: ["KONSA", "O'REILLY", "STONES", "GUÉHI", "CHALOBAH", "BURN", "JAMES", "SPENCE", "QUANSAH"],
    MID: ["RICE", "ANDERSON", "BELLINGHAM", "HENDERSON", "MAINOO", "ROGERS", "EZE"],
    FWD: ["SAKA", "KANE", "RASHFORD", "GORDON", "WATKINS", "MADUEKE", "TONEY"],
  },

  "França": {
    GK:  ["SAMBA", "MAIGNAN", "RISSER"],
    DEF: ["GUSTO", "DIGNE", "UPAMECANO", "KOUNDÉ", "KONATÉ", "SALIBA", "T. HERNANDEZ", "L. HERNANDEZ", "LACROIX"],
    MID: ["KONÉ", "TCHOUAMENI", "KANTÉ", "RABIOT", "ZAIRE-EMERY", "CHERKI", "AKLIOUCHE"],
    FWD: ["DEMBÉLÉ", "THURAM", "MBAPPÉ", "OLISE", "BARCOLA", "DOUÉ", "MATETA"],
  },

  "Alemanha": {
    GK:  ["NEUER", "BAUMANN", "NÜBEL"],
    DEF: ["RÜDIGER", "ANTON", "TAH", "KIMMICH", "SCHLOTTERBECK", "BROWN", "RAUM", "THIAW"],
    MID: ["PAVLOVIĆ", "GORETZKA", "LEWELING", "MUSIALA", "GROß", "STILLER", "WIRTZ", "SANÉ", "AMIRI", "NMECHA", "OUÉDRAOGO"],
    FWD: ["HAVERTZ", "WOLTEMADE", "BEIER", "UNDAV"],
  },

  "Gana": {
    GK:  ["ZIGI", "ANANG", "B. ASARE"],
    DEF: ["ALIDU SEIDU", "ADJETEY", "A. MUMIN", "MENSAH", "BABA", "OPOKU", "OPPONG", "LUCKASSEN", "SENEYA"],
    MID: ["YIRENKYI", "PARTEY", "SIBO", "SEMENYO", "OWUSU", "BOAKYE"],
    FWD: ["A. FATAWU", "J. AYEW", "ASANTE", "BONSU BAAH", "WILLIAMS", "KAMALDEEN", "NUAMAH", "PRINCE"],
  },

  "Japão": {
    GK:  ["SUZUKI", "OSAKO", "HAYAKAWA"],
    DEF: ["SUGAWARA", "TANIGUCHI", "ITAKURA", "NAGATOMO", "WATANABE", "SEKO", "H. ITO", "TOMIYASU", "J. SUZUKI"],
    MID: ["TANAKA", "KUBO", "DOAN", "DAIZEN", "NAKAMURA", "ITO", "KAMADA", "Y. SUZUKI", "SANO"],
    FWD: ["MACHINO", "GOTO", "AYASE", "OGAWA", "SHIOGAI"],
  },

  "México": {
    GK:  ["R. RANGEL", "C. ACEVEDO", "G. OCHOA"],
    DEF: ["J. SÁNCHEZ", "C. MONTES", "E. ÁLVAREZ", "J. VÁSQUEZ", "I. REYES", "M. CHÁVEZ", "J. GALLARDO"],
    MID: ["E. LIRA", "L. ROMO", "FIDALGO", "ORBELÍN", "O. VARGAS", "G. MORA", "L. CHÁVEZ", "B. GUTIÉRREZ"],
    FWD: ["RAÚL", "A. VEGA", "S. GIMÉNEZ", "A. GONZÁLEZ", "J. QUIÑONES", "C. HUERTA", "G. MARTÍNEZ", "R. ALVARADO"],
  },

  "Marrocos": {
    GK:  ["BONO", "EL KAJOUI", "TAGNAOUTI"],
    DEF: ["HAKIMI", "MAZRAOUI", "SAADANE", "EL OUAHDI", "ISSA", "RIAD", "BELAMMARI", "HALHAL", "SALAH-EDDINE"],
    MID: ["AMRABAT", "BOUADDI", "TALBI", "OUNAHI", "SAIBARI", "EL MOURABET", "YASSINE", "EL KHANNOUSS", "EL AYNAOUI"],
    FWD: ["RAHIMI", "BRAHIM", "SBAI", "EL KAABI", "AMAIMOUNI"],
  },

  "Países Baixos": {
    GK:  ["VERBRUGGEN", "ROEFS", "FLEKKEN"],
    DEF: ["GEERTRUIDA", "VIRGIL", "AKÉ", "VAN HECKE", "WIEFFER", "VAN DE VEN", "DUMFRIES", "HATO"],
    MID: ["DE ROON", "KLUIVERT", "GRAVENBERCH", "REIJNDERS", "TIL", "KOOPMEINERS", "F. DE JONG", "Q. TIMBER"],
    FWD: ["WEGHORST", "MEMPHIS", "GAKPO", "LANG", "MALEN", "BROBBEY", "SUMMERVILLE"],
  },

  "Noruega": {
    GK:  ["NYLAND", "TANGVIK", "SELVIK"],
    DEF: ["VASSBAKK AJER", "ØSTIGÅRD", "MØLLER WOLFE", "BJØRKAN", "HOLMGREN", "HEGGEM", "LANGÅS", "FALCHENER"],
    MID: ["THORSBY", "BERG", "BERGE", "ØDEGAARD", "AURSNES", "THORSTVEDT", "AASGAARD", "SCHJELDERUP", "BOBB", "HAUGE"],
    FWD: ["SØRLOTH", "BRAUT HAALAND", "STRAND LARSEN", "NUSA", "RYERSON"],
  },

  "Paraguai": {
    GK:  ["FERNÁNDEZ", "O. GILL", "OLVEIRA"],
    DEF: ["VELÁZQUEZ", "ALDERETE", "CÁCERES", "BALBUENA", "ALONSO", "CANALE", "G. GÓMEZ", "MAIDANA"],
    MID: ["SOSA", "D. GÓMEZ", "ALMIRÓN", "MAURÍCIO", "CUBAS", "BOBADILLA", "OJEDA", "GALARZA", "CABALLERO"],
    FWD: ["SANABRIA", "R. GAMARRA", "ARCE", "ENCISO", "ÁVALOS", "PITTA"],
  },

  "Portugal": {
    GK:  ["DIOGO COSTA", "JOSÉ SÁ", "RUI SILVA"],
    DEF: ["N. SEMEDO", "RÚBEN DIAS", "TOMÁS A.", "DALOT", "RENATO VEIGA", "G. INÁCIO", "JOÃO CANCELO", "SAMU", "N. MENDES"],
    MID: ["MATHEUS N.", "B. FERNANDES", "BERNARDO", "JOÃO NEVES", "R. NEVES", "VITINHA"],
    FWD: ["RONALDO", "G. RAMOS", "JOÃO FÉLIX", "TRINCÃO", "RAFA LEÃO", "NETO", "G. GUEDES", "F. CONCEIÇÃO"],
  },

  "Senegal": {
    GK:  ["Y. DIOUF", "MENDY", "DIAW"],
    DEF: ["SARR", "KOULIBALY", "SECK", "JAKOBS", "DIATTA", "NIAKHATÉ", "A. MENDY", "DIOUF"],
    MID: ["GANA", "P.I. CISS", "LAMINE", "P.M. SARR", "H. DIARRA", "BARA", "GUEYE"],
    FWD: ["A. DIAO", "BAMBA", "MANÉ", "N. JACKSON", "CHERIF", "NDIAYE", "ISMAILA", "I. MBAYE"],
  },

  "África do Sul": {
    GK:  ["WILLIAMS", "CHAINE", "GOSS"],
    DEF: ["MATULUDI", "NDAMANE", "MODIBA", "MBOKAZI", "KABINI", "SIBISI", "MUDAU", "OKON", "MAKHANYA", "CROSS"],
    MID: ["MOKOENA", "MBATHA", "ZWANE", "SITHOLE", "ADAMS"],
    FWD: ["APPOLLIS", "MOREMI", "FOSTER", "MOFOKENG", "MASEKO", "RAYNERS", "MAKGOPA", "SEBELEBELE"],
  },

  "Espanha": {
    GK:  ["RAYA", "JOAN GARCIA", "UNAI SIMON"],
    DEF: ["MARC PUBILL", "GRIMALDO", "ERIC", "M. LLORENTE", "PEDRO PORRO", "LAPORTE", "CUBARSI", "CUCURELLA"],
    MID: ["MERINO", "FABIAN", "GAVI", "ALEX B.", "RODRIGO", "ZUBIMENDI", "PEDRI"],
    FWD: ["FERRAN", "OLMO", "YEREMY", "WILLIAMS JR.", "LAMINE YAMAL", "OYARZABAL", "VÍCTOR M.V.", "B. IGLESIAS"],
  },

  "Suécia": {
    GK:  ["ZETTERSTRÖM", "V. JOHANSSON", "NORDFELDT"],
    DEF: ["LAGERBIELKE", "LINDELÖF", "HIEN", "GUDMUNDSSON", "H. JOHANSSON", "SVENSSON", "EKDAL", "STARFELT", "SMITH", "BERNHARDSSON", "STROUD"],
    MID: ["BERGVALL", "NYGREN", "SEMA", "KARLSTRÖM", "AYARI", "SVANBERG", "ZENELI"],
    FWD: ["ISAK", "ELANGA", "GYÖKERES", "NILSSON", "ALI"],
  },

  "Suíça": {
    GK:  ["KOBEL", "MVOGO", "KELLER"],
    DEF: ["MUHEIM", "WIDMER", "ELVEDI", "AKANJI", "RODRIGUEZ", "CÖMERT", "AMENDA", "JAQUEZ"],
    MID: ["ZAKARIA", "FREULER", "MANZAMBI", "XHAKA", "JASHARI", "SOW", "AEBISCHER", "RIEDER"],
    FWD: ["EMBOLO", "NDOYE", "FASSNACHT", "VARGAS", "OKAFOR", "AMDOUNI", "ITTEN"],
  },

  "Estados Unidos": {
    GK:  ["TURNER", "FREESE", "BRADY"],
    DEF: ["DEST", "RICHARDS", "A. ROBINSON", "TRUSTY", "M. ROBINSON", "REAM", "FREEMAN", "ARFSTEN", "MCKENZIE", "SCALLY"],
    MID: ["ADAMS", "REYNA", "MCKENNIE", "BERHALTER", "ROLDAN", "TILLMAN"],
    FWD: ["PEPI", "PULISIC", "AARONSON", "WRIGHT", "BALOGUN", "WEAH", "ZENDEJAS"],
  },

};

const NOMES_COMPLETOS = {
  "MASTIL": "Melvin Feycal MASTIL",
  "MANDI": "Aissa MANDI",
  "ABADA": "Achref ABADA",
  "TOUGAI": "Mohamed Amine TOUGAI",
  "BELAID": "Zineddine BELAID",
  "ZERROUKI": "Ramiz Larbi ZERROUKI",
  "MAHREZ": "Riyad Karim MAHREZ",
  "AOUAR": "Houssem-Eddine Chaabane AOUAR",
  "GOUIRI": "Amine Ferid GHOUIRI",
  "CHAIBI": "Fares CHAIBI",
  "HADJ MOUSSA": "Anis HADJ MOUSSA",
  "BENBOUALI": "Ahmed Nadhir BENBOUALI",
  "HADJAM": "Jaouen Djimmy HADJAM",
  "BOUDAOUI": "Hicham BOUDAOUI",
  "AIT NOURI": "Rayan AIT-NOURI",
  "BENBOT": "Oussama BENBOT",
  "BELGHALI": "Rafik BELGHALI",
  "AMOURA": "Mohammed Elamine AMOURA",
  "BENTALEB": "Nabil BENTALEB",
  "BOULBINA": "Adil BOULBINA",
  "BENSEBAINI": "Amir Selmane Rami BENSEBAINI",
  "MAZA": "Ibrahim MAZA",
  "ZIDANE": "Luca Zinedine ZIDANE",
  "TITRAOUI": "Yassine MEG TITRAOUI",
  "GHEDJEMIS": "Fares GHEDJEMIS",
  "CHERGUI": "Samir Sophian CHERGUI",
  "MUSSO": "Juan Agustin MUSSO",
  "SENESI": "Marcos Nicolás SENESI BARON",
  "TAGLIAFICO": "Nicolás Alejandro TAGLIAFICO",
  "MONTIEL": "Gonzalo Ariel MONTIEL",
  "PAREDES": "Leandro Daniel PAREDES",
  "MARTINEZ": "Lisandro MARTÍNEZ",
  "DE PAUL": "Rodrigo Javier DE PAUL",
  "BARCO": "Valentin BARCO",
  "J ALVAREZ": "Julian ALVAREZ",
  "MESSI": "Lionel Andrés MESSI",
  "LO CELSO": "Giovani LO CELSO",
  "RULLI": "Geronimo RULLI",
  "ROMERO": "Cristian Gabriel ROMERO",
  "PALACIOS": "Exequiel Alejandro PALACIOS",
  "N. GONZALEZ": "Nicolas Ivan GONZALEZ",
  "ALMADA": "Thiago Ezequiel ALMADA",
  "SIMEONE": "Giuliano SIMEONE",
  "NICO PAZ": "Nicolas PAZ MARTINEZ",
  "OTAMENDI": "Nicolas Hernan Gonzalo OTAMENDI",
  "MAC ALLISTER": "Alexis MAC ALLISTER",
  "LOPEZ": "Jose Manuel Alberto LOPEZ",
  "L. MARTINEZ": "Lautaro Javier MARTINEZ",
  "E. MARTINEZ": "Damián Emiliano MARTINEZ",
  "E. FERNANDEZ": "Enzo Jeremias FERNÁNDEZ",
  "MEDINA": "Facundo Axel MEDINA",
  "MOLINA": "Nahuel MOLINA LUCERO",
  "RYAN": "Mathew David RYAN",
  "DEGENEK": "Milos DEGENEK",
  "CIRCATI": "Alessandro CIRCATI",
  "ITALIANO": "Jacob Michael ITALIANO",
  "BOS": "Jordan Jacob BOS",
  "GERIA": "Jason Kato GERIA",
  "LECKIE": "Mathew Allan LECKIE",
  "METCALFE": "Connor Isaac METCALFE",
  "TOURE": "Mohamed A TOURE",
  "HRUSTIC": "Ajdin HRUSTIC",
  "MABIL": "Awer Bul MABIL",
  "IZZO": "Paul David IZZO",
  "O'NEILL": "Aiden Connor O'NEILL",
  "DEVLIN": "Cameron Peter DEVLIN",
  "TREWIN": "Kai Clifton TREWIN",
  "BEHICH": "Aziz BEHICH",
  "IRANKUNDA": "Nestory IRANKUNDA",
  "BEACH": "Patrick Thomas BEACH",
  "SOUTTAR": "Harry James SOUTTAR",
  "VOLPATO": "Cristian VOLPATO",
  "BURGESS": "Cameron Robert BURGESS",
  "IRVINE": "Jackson Alexander IRVINE",
  "VELUPILLAY": "Nishan Matthew VELUPILLAY",
  "OKON-ENGSTLER": "Paul Michael Junior OKON-ENGSTLER",
  "HERRINGTON": "Lucas HERRINGTON",
  "YENGI": "Tete Owen YENGI",
  "SCHLAGER": "Alexander SCHLAGER",
  "AFFENGRUBER": "David Leopold AFFENGRUBER",
  "DANSO": "Kevin DANSO",
  "XAVER": "Xaver SCHLAGER",
  "POSCH": "Stefan POSCH",
  "SEIWALD": "Nicolas SEIWALD",
  "ARNAUTOVIC": "Marko ARNAUTOVIC",
  "ALABA": "David ALABA",
  "SABITZER": "Marcel SABITZER",
  "GRILLITSCH": "Florian GRILLITSCH",
  "GREGORITSCH": "Michael GREGORITSCH",
  "WIEGELE": "Florian WIEGELE",
  "PENTZ": "Patrick PENTZ",
  "KALAJDZIC": "Saša KALAJDŽIĆ",
  "LIENHART": "Philipp LIENHART",
  "MWENE": "Phillip MWENE",
  "CHUKWUEMEKA": "Carney Chibueze CHUKWUEMEKA",
  "SCHMID": "Romano SCHMID",
  "LJUBICIC": "Dejan LJUBIČIĆ",
  "LAIMER": "Konrad LAIMER",
  "WIMMER": "Patrick WIMMER",
  "PRASS": "Alexander PRASS",
  "FRIEDL": "Marco FRIEDL",
  "WANNER": "Paul WANNER",
  "SVOBODA": "Michael SVOBODA",
  "SCHÖPF": "Alessandro Andre SCHÖPF",
  "COURTOIS": "Thibaut Nicolas M COURTOIS",
  "DEBAST": "Zeno Koen DEBAST",
  "THEATE": "Arthur Nicolas R THEATE",
  "MECHELE": "Brandon Erik MECHELE",
  "DE CUYPER": "Maxim Peter M DE CUYPER",
  "WITSEL": "Axel Laurent A WITSEL",
  "DE BRUYNE": "Kevin DE BRUYNE",
  "TIELEMANS": "Youri Marion A TIELEMANS",
  "LUKAKU": "Romelu LUKAKU BOLINGOLI",
  "TROSSARD": "Leandro TROSSARD",
  "DOKU": "Jeremy Baffour DOKU",
  "LAMMENS": "Senne LAMMENS",
  "PENDERS": "Mike Louis PENDERS",
  "LUKEBAKIO": "Dodi LUKEBAKIO NGANDOLI",
  "MEUNIER": "Thomas Andre A MEUNIER",
  "DE WINTER": "Koni DE WINTER",
  "DE KETELAERE": "Charles Marc S DE KETELAERE",
  "SEYS": "Joaquin Ronny SEYS",
  "MOREIRA JR": "Diego Manuel J DA SILVA MOREIRA",
  "VANAKEN": "Hans VANAKEN",
  "CASTAGNE": "Timothy CASTAGNE",
  "SAELEMAEKERS": "Alexis Jesse M SAELEMAEKERS",
  "RASKIN": "Nicolas Thierry Y RASKIN",
  "ONANA": "Amadou Ba Z MVOM ONANA",
  "NGOY": "Nathan NGOY",
  "FERNANDEZ-PARDO": "Matias FERNANDEZ-PARDO",
  "VASILJ": "Nikola VASILJ",
  "MUJAKIĆ": "Nihad MUJAKIĆ",
  "HADŽIKADUNIĆ": "Dennis HADŽIKADUNIĆ",
  "MUHAREMOVIĆ": "Tarik MUHAREMOVIĆ",
  "KOLAŠINAC": "Sead KOLAŠINAC",
  "TAHIROVIĆ": "Benjamin TAHIROVIĆ",
  "DEDIĆ": "Amar DEDIĆ",
  "GIGOVIĆ": "Armin GIGOVIĆ",
  "BAZDAR": "Samed BAZDAR",
  "DEMIROVIĆ": "Ermedin DEMIROVIĆ",
  "DŽEKO": "Edin DŽEKO",
  "JURKAS": "Mladen JURKAS",
  "BAŠIĆ": "Ivan BAŠIĆ",
  "SUNJIĆ": "Ivan SUNJIC",
  "MEMIĆ": "Amar MEMIĆ",
  "HADŽIAHMETOVIĆ": "Amir HADŽIAHMETOVIĆ",
  "BURNIĆ": "Dženis BURNIĆ",
  "KATIĆ": "Nikola KATIĆ",
  "ALAJBEGOVIĆ": "Kerim ALAJBEGOVIĆ",
  "BAJRAKTAREVIĆ": "Esmir BAJRAKTAREVIĆ",
  "RADELJIĆ": "Stjepan RADELJIĆ",
  "ZLOMISLIĆ": "Martin ZLOMISLIĆ",
  "TABAKOVIĆ": "Haris TABAKOVIĆ",
  "MALIĆ": "Arjan MALIĆ",
  "LUKIĆ": "Jovo LUKIĆ",
  "MAHMIĆ": "Ermin MAHMIĆ",
  "A. BECKER": "Alisson Ramsés BECKER",
  "EDERSON S.": "Ederson José DOS SANTOS LOURENÇO DA SILVA",
  "GABRIEL": "Gabriel DOS SANTOS MAGALHÃES",
  "MARQUINHOS": "Marcos AOÁS CORRÊA",
  "CASEMIRO": "Carlos Henrique CASIMIRO",
  "ALEX SANDRO": "Alex Sandro LOBO SILVA",
  "VINI JR.": "Vinícius José PAIXÃO DE OLIVEIRA JÚNIOR",
  "BRUNO G.": "Bruno GUIMARÃES RODRIGUEZ MOURA",
  "CUNHA": "Matheus SANTOS CARNEIRO DA CUNHA",
  "NEYMAR JR": "Neymar DA SILVA SANTOS JÚNIOR",
  "RAPHINHA": "Raphael DIAS BELLOLI",
  "WEVERTON": "Weverton PEREIRA DA SILVA",
  "DANILO": "Danilo Luiz DA SILVA",
  "BREMER": "Gleison Bremer SILVA NASCIMENTO",
  "LÉO PEREIRA": "Leonardo PEREIRA",
  "DOUGLAS S.": "Douglas DOS SANTOS JUSTINO DE MELO",
  "FABINHO": "Fábio Henrique TAVARES",
  "DANILO S.": "Danilo DOS SANTOS DE OLIVEIRA",
  "ENDRICK": "Endrick Felipe MOREIRA DE SOUSA PESSOA",
  "L. PAQUETÁ": "Lucas TOLENTINO COELHO DE LIMA",
  "L. HENRIQUE": "Luiz Henrique André ROSA DA SILVA",
  "MARTINELLI": "Gabriel TEODORO MARTINELLI SILVA",
  "EDERSON": "Ederson SANTANA DE MORAES",
  "IBAÑEZ": "Roger IBAÑEZ DA SILVA",
  "THIAGO": "Igor Thiago NASCIMENTO RODRIGUES",
  "RAYAN": "Rayan Vitor SIMPLÍCIO ROCHA",
  "VOZINHA": "Josimar José ÉVORA DIAS",
  "STOPIRA": "Ianique DOS SANTOS TAVARES",
  "BORGES": "Edilson Alberto MONTEIRO SANCHES BORGES",
  "LOPES": "Roberto Carlos LOPES",
  "COSTA": "Logan Evans COSTA",
  "KEVIN L.": "Kevin Lenini GONÇALVES PEREIRA DE PINA",
  "JOVANE": "Jovane Eduardo BORGES CABRAL",
  "JOÃO PAULO": "João Paulo MOREIRA FERNANDES",
  "BENCHIMOL": "Gilson BENCHIMOL TAVARES",
  "MONTEIRO": "Jamiro Gregory MONTEIRO ALVARENGA",
  "RODRIGUES": "Garry MENDES RODRIGUES",
  "MÁRCIO": "Márcio Salomão BRAZÃO DA ROSA",
  "LOPES CABRAL": "Sidny LOPES CABRAL",
  "D. DUARTE": "Deroy D'ENCARNAÇÃO DUARTE",
  "L. DUARTE": "Laros Michael D'ENCARNAÇÃO DUARTE",
  "Y. SEMEDO": "Jair SEMEDO MONTEIRO",
  "SEMEDO": "Willy Johnson SEMEDO AFONSO",
  "ARCANJO": "Telmo Emanuel GOMES ARCANJO",
  "LIVRAMENTO": "Dailon ROCHA LIVRAMENTO",
  "DA COSTA": "Nuno Miguel DA COSTA JÓIA",
  "MOREIRA": "Steven MOREIRA",
  "DOS SANTOS": "Carlos Joaquim ANTUNES DOS SANTOS",
  "WAGNER P.": "Wagner Fabrício CARDOSO DE PINA",
  "KELVIN": "Kelvin SPENCER PIRES",
  "HÉLIO": "Hélio Sandro OLIVEIRA ALVES VARELA",
  "ST. CLAIR": "Dayne Tristan ST. CLAIR",
  "JOHNSTON": "Alistair William JOHNSTON",
  "JONES": "Alfie Charles JONES",
  "DE FOUGEROLLES": "Luc ROLLET DE FOUGEROLLES",
  "WATERMAN": "Joel Robert WATERMAN",
  "CHOINIÈRE": "Mathieu CHOINIÈRE",
  "EUSTÁQUIO": "Stephen EUSTÁQUIO",
  "KONÉ": "Ismaël Kenneth Jordan KONÉ",
  "LARIN": "Cyle Christopher LARIN",
  "J. DAVID": "Jonathan Christian DAVID",
  "MILLAR": "Liam Alan MILLAR",
  "OLUWASEYI": "Tanitoluwa Oluwatimilehin OLUWASEYI",
  "CORNELIUS": "Derek Austin CORNELIUS",
  "SHAFFELBURG": "Jacob Everett SHAFFELBURG",
  "BOMBITO": "Moïse Bombito LUMPUNGU",
  "CRÉPEAU": "Maxime CRÉPEAU",
  "BUCHANAN": "Tajon Trevor BUCHANAN",
  "GOODMAN": "Owen Olamidayo GOODMAN",
  "DAVIES": "Alphonso Boyle DAVIES",
  "AHMED": "Ali AHMED",
  "OSORIO": "Jonathan OSORIO",
  "LARYEA": "Richmond Mamah LARYEA",
  "SIGUR": "Niko Kristian SIGUR",
  "PROMISE": "Promise Oluwatobi Emmanuel DAVID",
  "SALIBA": "Nathan-Dylan SALIBA",
  "NELSON": "Jayden NELSON",
  "OSPINA": "David OSPINA RAMÍREZ",
  "D. MUÑOZ": "Daniel MUÑOZ MEJÍA",
  "J. LUCUMÍ": "Jhon Janer LUCUMÍ BONILLA",
  "ARIAS": "Santiago ARIAS NARANJO",
  "K. CASTAÑO": "Kevin Duván CASTAÑO GIL",
  "RICHARD RÍOS": "Richard RÍOS MONTOYA",
  "LUIS DÍAZ": "Luis Fernando DÍAZ MARULANDA",
  "CARRASCAL": "Jorge Andrés CARRASCAL GUARDO",
  "CÓRDOBA": "Jhon Andrés CÓRDOBA COPETE",
  "JAMES": "James David RODRÍGUEZ RUBIO",
  "J. ARIAS": "Jhon Adolfo ARIAS ANDRADE",
  "C. VARGAS": "Camilo Andrés VARGAS GIL",
  "Y. MINA": "Yerry Fernando MINA GONZÁLEZ",
  "PUERTA": "Gustavo Adolfo PUERTA MOLANO",
  "PORTILLA": "Juan Camilo PORTILLA OROZCO",
  "J. LERMA": "Jefferson Andrés LERMA SOLÍS",
  "J. MOJICA": "Johan Andrés MOJICA PALACIO",
  "W. DITTA": "Willer Emilio DITTA PÉREZ",
  "C. HERNÁNDEZ": "Juan Camilo HERNÁNDEZ SUÁREZ",
  "QUINTERO": "Juan Fernando QUINTERO PANIAGUA",
  "CAMPAZ": "Jaminton Leandro CAMPAZ",
  "MACHADO": "Deiver MACHADO MENA",
  "SÁNCHEZ": "Davinson SÁNCHEZ MINA",
  "MONTERO": "Álvaro David MONTERO PERALES",
  "SUÁREZ": "Luis Javier SUÁREZ CHARRIS",
  "A. GÓMEZ": "Carlos Andrés GÓMEZ HINESTROZA",
  "MPASI": "Lionel Nzau MPASI",
  "WAN BISSAKA": "Aaron Wan BISSAKA",
  "KAPUADI": "Steve Nkanu KAPUADI",
  "TUANZEBE": "Axel TUANZEBE",
  "BATUBINSIKA": "Dylan Buduka BATUBINSIKA",
  "MUKAU": "Ngal'ayel MUKAU",
  "MBUKU": "Nathanaël MBUKU",
  "MOUTOUSSAMY": "Samuel Alain MOUTOUSSAMY",
  "CIPENGA": "Kibambe Brian CIPENGA",
  "BONGONDA": "Théo Mbulofeko Batombo BONGONDA",
  "KAKUTA": "Mambenga Gaël Roméo KAKUTA",
  "J. KAYEMBE": "Joris KAYEMBE DITU",
  "MESCHACK": "Meschack Lina ELIA",
  "SADIKI": "Noah Junior SADIKI",
  "TSHIBOLA": "Aaron TSHIBOLA",
  "FAYULU": "Timothy Bruce Munzoko FAYULU",
  "BAKAMBU": "Cédric BAKAMBU",
  "PICKEL": "Charles Monginda PICKEL",
  "MAYELE": "Mayele Fiston KALALA",
  "WISSA": "Yoane WISSA",
  "EPOLO": "Matthieu Luka EPOLO",
  "MBEMBA": "Mangulu Chancel MBEMBA",
  "BANZA": "Simon Bokote BANZA",
  "KALULU": "Gédéon Tchingoma Kyatengwa KALULU",
  "E. KAYEMBE": "Edo KAYEMBE",
  "MASUAKU": "Arthur Fuka MASUAKU KAWELA",
  "Y. FOFANA": "Yahia FOFANA",
  "O. DIOMANDE": "Ousmane DIOMANDE",
  "G. KONAN": "N'clomande Ghislain KONAN",
  "SERI": "Jean Michaël SERI",
  "SINGO": "Wilfried Stephane SINGO",
  "FOFANA": "Seko Mohamed FOFANA",
  "KOSSOUNOU": "Kouakou Odilon Dorgeless KOSSOUNOU",
  "KESSIE": "Franck Yannick KESSIE",
  "BONNY": "Ange-Yoan Laurent BONNY",
  "ADINGRA": "Simon ADINGRA",
  "YAN DIOMANDE": "Yan DIOMANDE",
  "WAHI": "Sepe Elye Delmas WAHI",
  "OPERI": "Christopher Tea Domoraud OPERI",
  "DIAKITE": "Oumar DIAKITE",
  "AMAD": "Amad DIALLO",
  "KONE": "Mohamed KONE",
  "G. DOUE": "Guela Maho-Lewis DOUE",
  "SANGARE": "Ibrahim SANGARE",
  "PEPE": "Nicolas PEPE",
  "AGBADOU": "Badobre Emmanuel Elysee Djedje AGBADOU",
  "NDICKA": "Obite Evan NDICKA",
  "GUESSAND": "Evann Ludovic Vidjannagni GUESSAND",
  "LAFONT": "Alban-Marc LAFONT",
  "GUIAGON": "Parfait GUIAGON",
  "INAO": "Christ Ravynel Inão OULAI",
  "LIVAKOVIĆ": "Dominik LIVAKOVIĆ",
  "STANIŠIĆ": "Josip STANIŠIĆ",
  "PONGRAČIĆ": "Marin PONGRAČIĆ",
  "GVARDIOL": "Joško GVARDIOL",
  "ĆALETA-CAR": "Duje ĆALETA-CAR",
  "ŠUTALO": "Josip ŠUTALO",
  "MORO": "Nikola MORO",
  "KOVAČIĆ": "Mateo KOVAČIĆ",
  "KRAMARIĆ": "Andrej KRAMARIĆ",
  "MODRIĆ": "Luka MODRIĆ",
  "BUDIMIR": "Ante BUDIMIR",
  "PANDUR": "Ivor PANDUR",
  "VLAŠIĆ": "Nikola VLAŠIĆ",
  "PERIŠIĆ": "Ivan PERIŠIĆ",
  "PAŠALIĆ": "Mario PAŠALIĆ",
  "BATURINA": "Martin BATURINA",
  "P. SUČIĆ": "Petar SUČIĆ",
  "JAKIĆ": "Kristijan JAKIĆ",
  "FRUK": "Toni FRUK",
  "MATANOVIĆ": "Igor MATANOVIĆ",
  "SUČIĆ": "Luka SUČIĆ",
  "VUŠKOVIĆ": "Luka VUŠKOVIĆ",
  "KOTARSKI": "Dominik KOTARSKI",
  "M. PAŠALIĆ": "Marco PAŠALIĆ",
  "ERLIĆ": "Martin ERLIĆ",
  "MUSA": "Petar MUSA",
  "GALÍNDEZ": "Hernán Ismael GALÍNDEZ",
  "TORRES": "Félix Eduardo TORRES CAICEDO",
  "HINCAPIE": "Piero Martín HINCAPIE REYNA",
  "ORDÓÑEZ": "Joel Leandro ORDÓÑEZ GUERRERO",
  "ALCÍVAR": "Jordy José ALCÍVAR MACÍAS",
  "PACHO": "Willian Joel PACHO TENORIO",
  "ESTUPIÑÁN": "Pervis Josué ESTUPIÑÁN TENORIO",
  "A. VALENCIA": "Anthony Lenin VALENCIA BAJAÑA",
  "YEBOAH ZAMORA": "John YEBOAH ZAMORA",
  "KENDRY": "Ray Kendry PÁEZ ANDRADE",
  "RODRÍGUEZ": "Kevin José RODRÍGUEZ CORTEZ",
  "RAMÍREZ": "Wellington Moisés RAMÍREZ PRECIADO",
  "E. VALENCIA": "Enner Remberto VALENCIA LASTRA",
  "MINDA": "Alan Steve MINDA GARCÍA",
  "VITE": "Pedro Jeampierre VITE UCA",
  "J. CAICEDO": "Jordy Josué CAICEDO MEDINA",
  "PRECIADO": "Ángelo Smit PRECIADO QUIÑÓNEZ",
  "CASTILLO": "Denil Daniel CASTILLO PRECIADO",
  "PLATA": "Gonzalo Jordy PLATA JIMÉNEZ",
  "ANGULO": "Nilson David ANGULO RAMÍREZ",
  "FRANCO": "Alan Steven FRANCO PALMA",
  "VALLE": "Gonzalo Roberto VALLE BUSTAMANTE",
  "M. CAICEDO": "Moisés Isaac CAICEDO COROZO",
  "ARÉVALO": "Jeremy Alberto ARÉVALO MERA",
  "POROZO": "Jackson Gabriel POROZO VERNAZA",
  "M. ELSHENAWY": "Mohamed Elsayed Mohamed ELSHENAWY GOMAA",
  "YASSER": "Yasser Ahmed Ibrahim ELHANAFY",
  "M. HANY": "Mohamed Hany Gamal ELDEMERDASH",
  "HOSSAM": "Hossam Abdelmegeed Abdelsalam ABDELMEGEED",
  "R. RABIA": "Ramy Hisham Abdelaziz Moustafa RABIA",
  "M. ABDELMONIEM": "Mohamed Abdelmoneim Elsayed M AHMED",
  "M. TREZEGUET": "Mahmoud Ahmed Ibrahim HASSAN",
  "E. ASHOUR": "Emam Ashour Metwaly ABDELGHANY",
  "ABDELKARIM": "Hamza Mohamed Abdelkarim E SELIM",
  "M. SALAH": "Mohamed Salah Hamed Mahrous GHALY",
  "ZICO": "Mostafa Mohamed Zaky ABDELRAOUF",
  "H. HASSAN": "Haissem Yousry Fouad A HASSAN",
  "A. FATOUH": "Ahmed Mohamed Aboelfetouh MOHAMED",
  "H. FATHY": "Hamdy Fathy Abdelhalim ABDEL FATTAH",
  "K. HAFEZ": "Karim Hafez Ramadan SEIFELDIN",
  "M. SOLIMAN": "Mahdy Mohamed Soliman IBRAHIM",
  "M. LASHIN": "Mohanad Mostafa Ahmed A LASHIN",
  "DONGA": "Nabil Emad Aly Elmahdy ALY",
  "M. ATTIA": "Marawan Attia Fahim GHALLAB",
  "I. ADEL": "Ibrahim Adel Aly Mohamed HASSAN",
  "M. SABER": "Mahmoud Saber Abdelmohsen H ABDELMOHSEN",
  "MARMOUSH": "Omar Khaled Mohamed Abdelsalam MARMOUSH",
  "SHOUBIR": "Mostafa Ahmed Abdelaziz Mohame SHOUBIR",
  "T. ALAA": "Tarek Alaa Abdelghaffar Abdel ELGEBALY",
  "ZIZO": "Ahmed Mostafa Mohamed SAYED",
  "M. ALAA": "Mohamed Alaaeldin Soliman M AHMED",
  "PICKFORD": "Jordan Lee PICKFORD",
  "KONSA": "Ezri Ngoyo KONSA",
  "O'REILLY": "Nico O'REILLY",
  "RICE": "Declan RICE",
  "STONES": "John STONES",
  "GUÉHI": "Addji Keaninkin Marc-Isreal GUÉHI",
  "SAKA": "Bukayo Ayoyinka SAKA",
  "ANDERSON": "Elliot Junior ANDERSON",
  "KANE": "Harry Edward KANE",
  "BELLINGHAM": "Jude Victor William BELLINGHAM",
  "RASHFORD": "Marcus RASHFORD",
  "CHALOBAH": "Trevoh Tom CHALOBAH",
  "D. HENDERSON": "Dean Bradley HENDERSON",
  "HENDERSON": "Jordan Brian HENDERSON",
  "BURN": "Daniel Johnson BURN",
  "MAINOO": "Kobbie Boateng MAINOO",
  "ROGERS": "Morgan Elliot ROGERS",
  "GORDON": "Anthony Michael GORDON",
  "WATKINS": "Oliver George Arthur WATKINS",
  "MADUEKE": "Chukwunonso Azuka Tristan MADUEKE",
  "EZE": "Eberechi Oluchi EZE",
  "TONEY": "Ivan Benjamin Elijah TONEY",
  "TRAFFORD": "James Harrington TRAFFORD",
  "SPENCE": "Diop Tehuti Djed-Hotep SPENCE",
  "QUANSAH": "Jarell Amorin QUANSAH",
  "SAMBA": "Brice Lauriche SAMBA",
  "GUSTO": "Malo Arthur GUSTO",
  "DIGNE": "Lucas DIGNE",
  "UPAMECANO": "Dayotchanculle Oswald UPAMECANO",
  "KOUNDÉ": "Jules Olivier KOUNDÉ",
  "DEMBÉLÉ": "Masour Ousmane DEMBÉLÉ",
  "TCHOUAMENI": "Aurélien Djani TCHOUAMENI",
  "THURAM": "Marcus Lilian THURAM-ULIEN",
  "MBAPPÉ": "Kylian MBAPPÉ LOTTIN",
  "OLISE": "Michael Akpovie OLISE",
  "BARCOLA": "Bradley Jean-Manuel Essolisa A BARCOLA",
  "KANTÉ": "N'golo KANTÉ",
  "RABIOT": "Adrien Thibault Marie RABIOT",
  "KONATÉ": "Ibrahima KONATÉ",
  "MAIGNAN": "Mike Peterson MAIGNAN",
  "ZAIRE-EMERY": "Warren Marie Jean-Pierre ZAÏRE-EMERY",
  "T. HERNANDEZ": "Théo Bernard François HERNANDEZ",
  "DOUÉ": "Désiré Nonka-Maho DOUÉ",
  "L. HERNANDEZ": "Lucas François Bernard HERNANDEZ",
  "MATETA": "Jean-Philippe MATETA",
  "RISSER": "Robin François Philippe RISSER",
  "CHERKI": "Mathis Rayan CHERKI",
  "AKLIOUCHE": "Maghnes AKLIOUCHE",
  "LACROIX": "Maxence Guy LACROIX",
  "NEUER": "Manuel Peter NEUER",
  "RÜDIGER": "Antonio RÜDIGER",
  "ANTON": "Waldemar ANTON",
  "TAH": "Jonathan Glao TAH",
  "PAVLOVIĆ": "Aleksandar PAVLOVIĆ",
  "KIMMICH": "Joshua Walter KIMMICH",
  "HAVERTZ": "Kai Lukas HAVERTZ",
  "GORETZKA": "Leon Christoph GORETZKA",
  "LEWELING": "Jamie Jaleel Jeremy LEWELING",
  "MUSIALA": "Jamal MUSIALA",
  "WOLTEMADE": "Nick WOLTEMADE",
  "BAUMANN": "Oliver BAUMANN",
  "GROß": "Pascal Alexander GROß",
  "BEIER": "Maximilian BEIER",
  "SCHLOTTERBECK": "Nico Cédric SCHLOTTERBECK",
  "STILLER": "Angelo Nicolas STILLER",
  "WIRTZ": "Florian Richard WIRTZ",
  "BROWN": "Nathaniel Christopher BROWN",
  "SANÉ": "Leroy Aziz SANÉ",
  "AMIRI": "Nadiem AMIRI",
  "NÜBEL": "Alexander NÜBEL",
  "RAUM": "David RAUM",
  "NMECHA": "Felix Kalu NMECHA",
  "THIAW": "Malick THIAW",
  "OUÉDRAOGO": "Forzan Assan OUÉDRAOGO",
  "UNDAV": "Deniz UNDAV",
  "ZIGI": "Lawrence Ati ZIGI",
  "ALIDU SEIDU": "Alidu SEIDU",
  "YIRENKYI": "Caleb Marfo YIRENKYI",
  "ADJETEY": "Jonas Adjei ADJETEY",
  "PARTEY": "Thomas Teye PARTEY",
  "A. MUMIN": "Abdul Mumin SULEMAN",
  "A. FATAWU": "Abdul Fatawu ISSAHAKU",
  "SIBO": "Kwasi SIBO",
  "J. AYEW": "Jordan Pierre AYEW",
  "ASANTE": "Solomon Brandon Michael Clarke THOMAS-ASANTE",
  "SEMENYO": "Antoine Serlom SEMENYO",
  "ANANG": "Joseph Tetteh ANANG",
  "BONSU BAAH": "Christopher Bonsu BAAH",
  "MENSAH": "Gideon MENSAH",
  "OWUSU": "Elisha OWUSU",
  "B. ASARE": "Benjamin ASARE",
  "BABA": "Abdul Rahman BABA",
  "OPOKU": "Jerome OPOKU",
  "WILLIAMS": "Iñaki WILLIAMS ARTHUER",
  "BOAKYE": "Augustine BOAKYE",
  "OPPONG": "Kojo Peprah OPPONG",
  "KAMALDEEN": "Kamal Deen SULEMANA",
  "LUCKASSEN": "Derrick LUCKASSEN",
  "NUAMAH": "Ernest Nuamah APPIAH",
  "PRINCE": "Prince Kwabena ADU",
  "SENEYA": "Marvin Elom SENAYA",
  "SUZUKI": "Zion SUZUKI",
  "SUGAWARA": "Yukinari SUGAWARA",
  "TANIGUCHI": "Shogo TANIGUCHI",
  "ITAKURA": "Kou ITAKURA",
  "NAGATOMO": "Yuto NAGATOMO",
  "MACHINO": "Shuto MACHINO",
  "TANAKA": "Ao TANAKA",
  "KUBO": "Takefusa KUBO",
  "GOTO": "Keisuke GOTO",
  "DOAN": "Ritsu DOAN",
  "DAIZEN": "Daizen MAEDA",
  "OSAKO": "Keisuke OSAKO",
  "NAKAMURA": "Keito NAKAMURA",
  "ITO": "Junya ITO",
  "KAMADA": "Daichi KAMADA",
  "WATANABE": "Tsuyoshi WATANABE",
  "Y. SUZUKI": "Yuito SUZUKI",
  "AYASE": "Ayase UEDA",
  "OGAWA": "Koki OGAWA",
  "SEKO": "Ayumu SEKO",
  "H. ITO": "Hiroki ITO",
  "TOMIYASU": "Takehiro TOMIYASU",
  "HAYAKAWA": "Tomoki HAYAKAWA",
  "SANO": "Kaishu SANO",
  "J. SUZUKI": "Junnosuke SUZUKI",
  "SHIOGAI": "Kento SHIOGAI",
  "R. RANGEL": "José Raúl RANGEL AGUILAR",
  "J. SÁNCHEZ": "Jorge Eduardo SÁNCHEZ RAMOS",
  "C. MONTES": "César Jasib MONTES CASTRO",
  "E. ÁLVAREZ": "Edson Omar ÁLVAREZ VELÁZQUEZ",
  "J. VÁSQUEZ": "Johan Felipe VÁSQUEZ IBARRA",
  "E. LIRA": "Erik Antonio LIRA MÉNDEZ",
  "L. ROMO": "Luis Francisco ROMO BARRÓN",
  "FIDALGO": "Álvaro FIDALGO FERNÁNDEZ",
  "RAÚL": "Raúl Alonso JIMÉNEZ RODRÍGUEZ",
  "A. VEGA": "Ernesto Alexis VEGA ROJAS",
  "S. GIMÉNEZ": "Santiago Tomás GIMÉNEZ",
  "C. ACEVEDO": "Carlos ACEVEDO LÓPEZ",
  "G. OCHOA": "Francisco Guillermo OCHOA MAGAÑA",
  "A. GONZÁLEZ": "Armando GONZÁLEZ ALBA",
  "I. REYES": "Israel REYES ROMERO",
  "J. QUIÑONES": "Julián Andrés QUIÑONES QUIÑONES",
  "ORBELÍN": "Orbelín PINEDA ALVARADO",
  "O. VARGAS": "Obed Gómez VARGAS",
  "G. MORA": "Gilberto Rafael MORA ZAMBRANO",
  "M. CHÁVEZ": "Mateo CHÁVEZ GARCÍA",
  "C. HUERTA": "César Saúl HUERTA VALERA",
  "G. MARTÍNEZ": "Guillermo MARTÍNEZ AYALA",
  "J. GALLARDO": "Jesús Daniel GALLARDO VASCONCELOS",
  "L. CHÁVEZ": "Luis Gerardo CHÁVEZ MAGALLÓN",
  "R. ALVARADO": "Roberto Carlos ALVARADO HERNÁNDEZ",
  "B. GUTIÉRREZ": "Brian GUTIÉRREZ",
  "BONO": "Yassine BOUNOU",
  "HAKIMI": "Achraf HAKIMI",
  "MAZRAOUI": "Noussair MAZRAOUI",
  "AMRABAT": "Sofyan AMRABAT",
  "SAADANE": "Marwane SAADANE",
  "BOUADDI": "Ayyoub BOUADDI",
  "TALBI": "Chemsdine TALBI",
  "OUNAHI": "Azz-Eddine OUNAHI",
  "RAHIMI": "Soufiane RAHIMI",
  "BRAHIM": "Brahim ABDELKADER DIAZ",
  "SAIBARI": "Ismael SAIBARI",
  "EL KAJOUI": "Monir EL KAJOUI",
  "EL OUAHDI": "Zakaria EL OUAHDI",
  "ISSA": "Issa Laye Lucas Jean DIOP",
  "EL MOURABET": "Samir EL MOURABET",
  "YASSINE": "Gessime Ben Youssef Mustapha YASSINE",
  "SBAI": "Mohamed Amine SBAI",
  "RIAD": "Chadi RIAD",
  "BELAMMARI": "Youssef BELAMMARI",
  "EL KAABI": "Ayoub EL KAABI",
  "AMAIMOUNI": "Ayoube AMAIMOUNI",
  "TAGNAOUTI": "Ahmed Reda TAGNAOUTI",
  "EL KHANNOUSS": "Bilal EL KHANNOUSS",
  "EL AYNAOUI": "Neil Yoni EL AYNAOUI",
  "HALHAL": "Redouane HALHAL",
  "SALAH-EDDINE": "Anass SALAH EDDINE",
  "VERBRUGGEN": "Bart VERBRUGGEN",
  "GEERTRUIDA": "Lutsharel Emiliano GEERTRUIDA",
  "DE ROON": "Marten Elco DE ROON",
  "VIRGIL": "Virgil VAN DIJK",
  "AKÉ": "Nathan Benjamin AKÉ",
  "VAN HECKE": "Jan-Paul VAN HECKE",
  "KLUIVERT": "Justin Dean KLUIVERT",
  "GRAVENBERCH": "Ryan Jiro GRAVENBERCH",
  "WEGHORST": "Wout François Maria WEGHORST",
  "MEMPHIS": "Memphis DEPAY",
  "GAKPO": "Cody Mathès GAKPO",
  "WIEFFER": "Mats Henrik Berne WIEFFER",
  "ROEFS": "Robin Gerardus Petrus ROEFS",
  "REIJNDERS": "Tijjani Martinus Jan REIJNDERS",
  "VAN DE VEN": "Micky VAN DE VEN",
  "TIL": "Guus Berend TIL",
  "LANG": "Noa Noëll LANG",
  "MALEN": "Donyell MALEN",
  "BROBBEY": "Brian Ebenezer Adjei BROBBEY",
  "KOOPMEINERS": "Teun KOOPMEINERS",
  "F. DE JONG": "Frenkie DE JONG",
  "DUMFRIES": "Denzel Justus Morris DUMFRIES",
  "FLEKKEN": "Mark Maria Hubertus FLEKKEN",
  "SUMMERVILLE": "Crysencio Jilbert Sylverio Cir SUMMERVILLE",
  "HATO": "Jorrel Evan HATO",
  "Q. TIMBER": "Quinten Ryan Crispito TIMBER",
  "NYLAND": "Ørjan Haskjold NYLAND",
  "THORSBY": "Morten THORSBY",
  "VASSBAKK AJER": "Kristoffer Vassbakk Kopp AJER",
  "ØSTIGÅRD": "Leo Skiri ØSTIGARD",
  "MØLLER WOLFE": "David Møller WOLFE",
  "BERG": "Patrick BERG",
  "SØRLOTH": "Alexander SØRLOTH",
  "BERGE": "Sander Gard Bolin BERGE",
  "BRAUT HAALAND": "Erling Braut HAALAND",
  "ØDEGAARD": "Martin ØDEGAARD",
  "STRAND LARSEN": "Jørgen Strand LARSEN",
  "TANGVIK": "Sander TANGVIK",
  "SELVIK": "Egil SELVIK",
  "AURSNES": "Fredrik AURSNES",
  "BJØRKAN": "Fredrik André BJØRKAN",
  "HOLMGREN": "Marcus Holmgren PEDERSEN",
  "HEGGEM": "Torbjørn Lysaker HEGGEM",
  "THORSTVEDT": "Kristian THORSTVEDT",
  "AASGAARD": "Thelonious Gerard AASGAARD",
  "NUSA": "Antonio Eromonsele Nordby NUSA",
  "SCHJELDERUP": "Andreas Rædergård SCHJELDERUP",
  "BOBB": "Oscar BOBB",
  "HAUGE": "Jens Petter HAUGE",
  "LANGÅS": "Sondre Klingen LANGÅS",
  "FALCHENER": "Henrik Sælebakke FALCHENER",
  "RYERSON": "Julian RYERSON",
  "FERNÁNDEZ": "Roberto Junior FERNANDEZ TORRES",
  "VELÁZQUEZ": "Victor Gustavo VELAZQUEZ RAMOS",
  "ALDERETE": "Omar Federico ALDERETE FERNANDEZ",
  "CÁCERES": "Juan Jose CACERES",
  "BALBUENA": "Fabián Cornelio BALBUENA GONZÁLEZ",
  "ALONSO": "Júnior Osmar Ignacio ALONSO MUJICA",
  "SOSA": "Ramón SOSA ACOSTA",
  "D. GÓMEZ": "Diego Alexander GOMEZ AMARILLA",
  "SANABRIA": "Arnaldo Antonio SANABRIA AYALA",
  "ALMIRÓN": "Miguel Angel ALMIRON REJALA",
  "MAURÍCIO": "Mauricio MAGALHAES PRADO",
  "O. GILL": "Orlando Daniel GILL NOLDIN",
  "CANALE": "Jose Maria CANALE DOMINGUEZ",
  "CUBAS": "Adrián Andrés CUBAS",
  "G. GÓMEZ": "Gustavo Raul GÓMEZ PORTILLO",
  "BOBADILLA": "Damián Josue BOBADILLA BENITEZ",
  "R. GAMARRA": "Alejandro Sebastian ROMERO GAMARRA",
  "ARCE": "Alex Adrian ARCE BARRIOS",
  "ENCISO": "Julio Cesar ENCISO ESPINOLA",
  "OJEDA": "Braian Oscar OJEDA RODRIGUEZ",
  "ÁVALOS": "Gabriel AVALOS STUMPFS",
  "OLVEIRA": "Gastón Hernán OLVEIRA ECHEVERRIA",
  "GALARZA": "Matias GALARZA FONDA",
  "CABALLERO": "Gustavo Ruben CABALLERO GONZALEZ",
  "PITTA": "Isidro Miguel PITTA SALDIVAR",
  "MAIDANA": "Alexandro MAIDANA MENDIETA",
  "DIOGO COSTA": "Diogo MEIRELES DA COSTA",
  "N. SEMEDO": "Nélson CABRAL SEMEDO",
  "RÚBEN DIAS": "Rúben DOS SANTOS GATO ALVES DIAS",
  "TOMÁS A.": "Tomás LEMOS ARAUJO",
  "DALOT": "José Diogo DALOT TEIXEIRA",
  "MATHEUS N.": "Matheus Luiz NUNES",
  "RONALDO": "Cristiano Ronaldo DOS SANTOS AVEIRO",
  "B. FERNANDES": "Bruno Miguel BORGES FERNANDES",
  "G. RAMOS": "Gonçalo MATIAS RAMOS",
  "BERNARDO": "Bernardo MOTA VEIGA DE CARVALHO E SILVA",
  "JOÃO FÉLIX": "João FÉLIX SEQUEIRA",
  "JOSÉ SÁ": "José Pedro MALHEIRO DE SÁ",
  "RENATO VEIGA": "Renato DA PALMA VEIGA",
  "G. INÁCIO": "Gonçalo BERNARDO INACIO",
  "JOÃO NEVES": "João Pedro GONÇALVES NEVES",
  "TRINCÃO": "Francisco António MACHADO MOTA DE CASTRO TRINCÃO",
  "RAFA LEÃO": "Rafael Alexandre DA CONCEIÇÃO LEÃO",
  "NETO": "Pedro LOMBA NETO",
  "G. GUEDES": "Gonçalo Manuel GANCHINHO GUEDES",
  "JOÃO CANCELO": "João Pedro CAVACO CANCELO",
  "R. NEVES": "Rúben Diogo DA SILVA NEVES",
  "RUI SILVA": "Rui Tiago DANTAS DA SILVA",
  "VITINHA": "Vítor MACHADO FERREIRA",
  "SAMU": "Samuel DE ALMEIDA COSTA",
  "N. MENDES": "Nuno Alexandre TAVARES MENDES",
  "F. CONCEIÇÃO": "Francisco FERNANDES DA CONCEIÇÃO",
  "Y. DIOUF": "Yehvann Djibril Victor DIOUF",
  "SARR": "Mamadou SARR",
  "KOULIBALY": "Kalidou KOULIBALY",
  "SECK": "Abdoulaye SECK",
  "GANA": "Idrissa Gana GUEYE",
  "P.I. CISS": "Ismaila Pathe CISS",
  "A. DIAO": "Assane DIAO",
  "LAMINE": "Lamine CAMARA",
  "BAMBA": "Cheikh Ahmadou Bamba Mbacke DIENG",
  "MANÉ": "Sadio MANE",
  "N. JACKSON": "Nicolas JACKSON",
  "CHERIF": "Pape Cherif NDIAYE",
  "NDIAYE": "Iliman Cheikh Baroy NDIAYE",
  "JAKOBS": "Ismail Joshua JAKOBS",
  "DIATTA": "Krepin DIATTA",
  "MENDY": "Edouard Osoque MENDY",
  "P.M. SARR": "Pape Matar SARR",
  "ISMAILA": "Ismaila SARR",
  "NIAKHATÉ": "Moussa NIAKHATE",
  "I. MBAYE": "Ibrahim MBAYE",
  "H. DIARRA": "Mouhamadou Habib Mbacke DIARRA",
  "BARA": "Bara Sapoko NDIAYE",
  "DIAW": "Mory DIAW",
  "A. MENDY": "Antoine Alpha MENDY",
  "DIOUF": "El Hadji Malick DIOUF",
  "GUEYE": "Pape Alassane GUEYE",
  "MATULUDI": "Tholo Thabang MATULUDI",
  "NDAMANE": "Khulumani NDAMANE",
  "MOKOENA": "Teboho MOKOENA",
  "MBATHA": "Thalente Wandile MBATHA",
  "MODIBA": "Aubrey Maphosa MODIBA",
  "APPOLLIS": "Oswin Reagan APPOLLIS",
  "MOREMI": "Tshepang MOREMI",
  "FOSTER": "Lyle Brent FOSTER",
  "MOFOKENG": "Relebohile MOFOKENG",
  "ZWANE": "Themba ZWANE",
  "MASEKO": "Thapelo MASEKO",
  "SITHOLE": "Sphephelo S'miso SITHOLE",
  "MBOKAZI": "Mbekezeli Mfanufikile MBOKAZI",
  "RAYNERS": "Iqraam RAYNERS",
  "CHAINE": "Sipho Justin CHAINE",
  "MAKGOPA": "Sekotori Evidence MAKGOPA",
  "KABINI": "Samukele Alucious KABINI",
  "SIBISI": "Nkosinathi Emmanuel SIBISI",
  "MUDAU": "Khuliso Johnson MUDAU",
  "OKON": "Ime Daniel OKON",
  "GOSS": "Stuart Ricardo GOSS",
  "ADAMS": "Jayden Oswin ADAMS",
  "MAKHANYA": "Olwethu Mpilwerihle MAKHANYA",
  "SEBELEBELE": "Kamogelo Michael SEBELEBELE",
  "CROSS": "Bradley Paul CROSS",
  "RAYA": "David RAYA MARTIN",
  "MARC PUBILL": "Marc PUBILL PAGES",
  "GRIMALDO": "Alejandro GRIMALDO GARCÍA",
  "ERIC": "Eric GARCIA MARTRET",
  "M. LLORENTE": "Marcos LLORENTE MORENO",
  "MERINO": "Mikel MERINO ZAZÓN",
  "FERRAN": "Ferran TORRES GARCÍA",
  "FABIAN": "Fabian RUIZ PEÑA",
  "GAVI": "Pablo PAEZ GAVIRA",
  "OLMO": "Daniel OLMO CARVAJAL",
  "YEREMY": "Yeremy Jesús PINO SANTOS",
  "PEDRO PORRO": "Pedro Antonio PORRO SAUCEDA",
  "JOAN GARCIA": "Joan GARCIA PONS",
  "LAPORTE": "Aymeric LAPORTE FEVRE",
  "ALEX B.": "Alejandro BAENA RODRIGUEZ",
  "RODRIGO": "Rodrigo HERNÁNDEZ CASCANTE",
  "WILLIAMS JR.": "Nicholas WILLIAMS ARTHUER",
  "ZUBIMENDI": "Martin ZUBIMENDI IBAÑEZ",
  "LAMINE YAMAL": "Lamine Yamal NASRAOUI EBANA",
  "PEDRI": "Pedro GONZÁLEZ LÓPEZ",
  "OYARZABAL": "Mikel OYARZABAL UGARTE",
  "CUBARSI": "Pau CUBARSI I PAREDES",
  "UNAI SIMON": "Unai SIMON MENDIBIL",
  "CUCURELLA": "Marc CUCURELLA SASETA",
  "VÍCTOR M.V.": "Victor MUÑOZ VILLANUEVA",
  "B. IGLESIAS": "Borja IGLESIAS QUINTAS",
  "ZETTERSTRÖM": "Jacob Mikael WIDELL ZETTERSTRÖM",
  "LAGERBIELKE": "Gustaf Johan LAGERBIELKE",
  "LINDELÖF": "Victor Jörgen NILSSON LINDELÖF",
  "HIEN": "Isak Malcolm Kwaku HIEN",
  "GUDMUNDSSON": "Gabriel Johan GUDMUNDSSON",
  "H. JOHANSSON": "Herman Nils JOHANSSON",
  "BERGVALL": "Lucas Erik Holger BERGVALL",
  "SVENSSON": "Daniel Jonathan SVENSSON",
  "ISAK": "Alexander ISAK",
  "NYGREN": "Erik Benjamin NYGREN",
  "ELANGA": "Anthony David Junior ELANGA",
  "V. JOHANSSON": "Tobias Viktor JOHANSSON",
  "SEMA": "Ken SEMA",
  "EKDAL": "Hjalmar EKDAL",
  "STARFELT": "Carl Anders Theodor STARFELT",
  "KARLSTRÖM": "Jesper Kewe KARLSTRÖM",
  "GYÖKERES": "Viktor Einar GYÖKERES",
  "AYARI": "Yasin AYARI",
  "SVANBERG": "Mattias Olof SVANBERG",
  "SMITH": "Eric Anders SMITH",
  "BERNHARDSSON": "Alexander Olof BERNHARDSSON",
  "ZENELI": "Besfort ZENELI",
  "NORDFELDT": "Bo Kristoffer NORDFELDT",
  "STROUD": "Elliot Karl STROUD",
  "NILSSON": "Håkan Gustaf NILSSON",
  "ALI": "Taha Abdi ALI",
  "KOBEL": "Gregor KOBEL",
  "MUHEIM": "Miro Max Maria MUHEIM",
  "WIDMER": "Silvan Dominic WIDMER",
  "ELVEDI": "Nico ELVEDI",
  "AKANJI": "Manuel Obafemi AKANJI",
  "ZAKARIA": "Denis Lemi ZAKARIA LAKO LADO",
  "EMBOLO": "Breel Donald EMBOLO",
  "FREULER": "Remo Marco FREULER",
  "MANZAMBI": "Johan Kula MANZAMBI",
  "XHAKA": "Granit XHAKA",
  "NDOYE": "Dan NDOYE",
  "MVOGO": "Yvon Landry MVOGO NGANOMA",
  "RODRIGUEZ": "Ricardo Ivan RODRIGUEZ ARAYA",
  "JASHARI": "Ardon JASHARI",
  "SOW": "Mohameth Djibril Ibrahima SOW",
  "FASSNACHT": "Christian Andreas FASSNACHT",
  "VARGAS": "Ruben Estephan VARGAS MARTINEZ",
  "CÖMERT": "Eray Ervin CÖMERT",
  "OKAFOR": "Noah Arinzechukwu OKAFOR",
  "AEBISCHER": "Michel AEBISCHER",
  "KELLER": "Marvin KELLER",
  "RIEDER": "Fabian RIEDER",
  "AMDOUNI": "Mohamed Zeki AMDOUNI",
  "AMENDA": "Aurèle Florian AMENDA",
  "JAQUEZ": "Luca Antony JAQUEZ",
  "ITTEN": "Cedric Jan ITTEN",
  "TURNER": "Matthew Charles TURNER",
  "DEST": "Sergiño Gianni DEST",
  "RICHARDS": "Christopher Jeffrey RICHARDS",
  "A. ROBINSON": "Antonee ROBINSON",
  "TRUSTY": "Auston Levi Jesaiah TRUSTY",
  "REYNA": "Giovanni Alejandro REYNA",
  "MCKENNIE": "Weston James Earl MCKENNIE",
  "PEPI": "Ricardo Daniel PEPI",
  "PULISIC": "Christian Mate PULISIC",
  "AARONSON": "Brenden Russell AARONSON",
  "M. ROBINSON": "Miles Gordon ROBINSON",
  "REAM": "Timothy Michael REAM",
  "BERHALTER": "Sebastian Matthew BERHALTER",
  "ROLDAN": "Cristian ROLDAN",
  "FREEMAN": "Alexander Michael FREEMAN",
  "TILLMAN": "Malik Leon TILLMAN",
  "ARFSTEN": "Maximilian Michael ARFSTEN",
  "WRIGHT": "Haji Amir WRIGHT",
  "BALOGUN": "Folarin Jolaoluwa BALOGUN",
  "WEAH": "Timothy Tarpeh WEAH",
  "MCKENZIE": "Mark Alexander MCKENZIE",
  "SCALLY": "Joseph Michael SCALLY",
  "FREESE": "Matthew Andrew Geary FREESE",
  "BRADY": "Christopher Keith BRADY",
  "ZENDEJAS": "Alejandro ZENDEJAS SAAVEDRA",
};

const POS_LABEL = { GK: 'GK', DEF: 'DEF', MID: 'MID', FWD: 'ATK' };

function getJogadoresPorTime(nomeTime) {
  const e = ELENCOS[nomeTime];
  if (!e) return [];
  if (Array.isArray(e)) return e;
  return [...(e.GK||[]),...(e.DEF||[]),...(e.MID||[]),...(e.FWD||[])];
}

function getJogadoresComPosicao(nomeTime) {
  const e = ELENCOS[nomeTime];
  if (!e) return [];
  if (Array.isArray(e)) return e.map(n => ({ pos: '?', nome: n }));
  const result = [];
  for (const pos of ['GK','DEF','MID','FWD']) {
    for (const nome of (e[pos]||[])) result.push({ pos: POS_LABEL[pos], nome });
  }
  return result;
}

function getJogadoresJogo(timeHome, timeAway) {
  return {
    home: { nome: timeHome, jogadores: getJogadoresPorTime(timeHome) },
    away: { nome: timeAway, jogadores: getJogadoresPorTime(timeAway) }
  };
}