// Fotos dos jogadores — gerado automaticamente via GitHub Actions
// CDN: jsDelivr → github.com/Rufinorris/bolao-copa-2026/fotos/

const FOTOS = {
  "ZIDANE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZIDANE.jpg',
  "MANDI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MANDI.jpg',
  "BELAID": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BELAID.jpg',
  "HADJAM": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HADJAM.jpg',
  "CHERGUI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CHERGUI.jpg',
  "ZERROUKI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZERROUKI.jpg',
  "BOUDAOUI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BOUDAOUI.jpg',
  "BENTALEB": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BENTALEB.jpg',
  "MAZA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAZA.jpg',
  "MAHREZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAHREZ.jpg',
  "GOUIRI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GOUIRI.jpg',
  "HADJ MOUSSA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HADJ_MOUSSA.jpg',
  "BENBOUALI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BENBOUALI.jpg',
  "BOULBINA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BOULBINA.jpg',
  "MUSSO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MUSSO.jpg',
  "RULLI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RULLI.jpg',
  "E. MARTINEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/E_MARTINEZ.jpg',
  "TAGLIAFICO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TAGLIAFICO.jpg',
  "MONTIEL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MONTIEL.jpg',
  "MARTINEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MARTINEZ.jpg',
  "ROMERO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ROMERO.jpg',
  "OTAMENDI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OTAMENDI.jpg',
  "MEDINA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MEDINA.jpg',
  "PAREDES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PAREDES.jpg',
  "BARCO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BARCO.jpg',
  "LO CELSO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LO_CELSO.jpg',
  "PALACIOS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PALACIOS.jpg',
  "MAC ALLISTER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAC_ALLISTER.jpg',
  "E. FERNANDEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/E_FERNANDEZ.jpg',
  "J ALVAREZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/J_ALVAREZ.jpg',
  "MESSI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MESSI.jpg',
  "ALMADA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ALMADA.jpg',
  "SIMEONE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SIMEONE.jpg',
  "NICO PAZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NICO_PAZ.jpg',
  "LOPEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LOPEZ.jpg',
  "L. MARTINEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/L_MARTINEZ.jpg',
  "RYAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RYAN.jpg',
  "IZZO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/IZZO.jpg',
  "BEACH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BEACH.jpg',
  "DEGENEK": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DEGENEK.jpg',
  "CIRCATI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CIRCATI.jpg',
  "ITALIANO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ITALIANO.jpg',
  "BOS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BOS.jpg',
  "GERIA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GERIA.jpg',
  "TREWIN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TREWIN.jpg',
  "BEHICH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BEHICH.jpg',
  "SOUTTAR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SOUTTAR.jpg',
  "BURGESS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BURGESS.jpg',
  "HERRINGTON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HERRINGTON.jpg',
  "METCALFE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/METCALFE.jpg',
  "DEVLIN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DEVLIN.jpg',
  "IRVINE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/IRVINE.jpg',
  "LECKIE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LECKIE.jpg',
  "HRUSTIC": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HRUSTIC.jpg',
  "MABIL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MABIL.jpg',
  "IRANKUNDA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/IRANKUNDA.jpg',
  "VOLPATO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VOLPATO.jpg',
  "VELUPILLAY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VELUPILLAY.jpg',
  "YENGI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/YENGI.jpg',
  "SCHLAGER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SCHLAGER.jpg',
  "PENTZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PENTZ.jpg',
  "DANSO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DANSO.jpg',
  "POSCH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/POSCH.jpg',
  "ALABA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ALABA.jpg',
  "LIENHART": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LIENHART.jpg',
  "MWENE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MWENE.jpg',
  "FRIEDL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FRIEDL.jpg',
  "SVOBODA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SVOBODA.jpg',
  "XAVER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/XAVER.jpg',
  "SEIWALD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SEIWALD.jpg',
  "SABITZER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SABITZER.jpg',
  "GRILLITSCH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GRILLITSCH.jpg',
  "SCHMID": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SCHMID.jpg',
  "LJUBICIC": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LJUBICIC.jpg',
  "LAIMER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LAIMER.jpg',
  "PRASS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PRASS.jpg',
  "WANNER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WANNER.jpg',
  "SCHÖPF": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SCHOPF.jpg',
  "ARNAUTOVIC": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ARNAUTOVIC.jpg',
  "GREGORITSCH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GREGORITSCH.jpg',
  "KALAJDZIC": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KALAJDZIC.jpg',
  "WIMMER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WIMMER.jpg',
  "COURTOIS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/COURTOIS.jpg',
  "LAMMENS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LAMMENS.jpg',
  "DEBAST": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DEBAST.jpg',
  "THEATE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/THEATE.jpg',
  "MECHELE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MECHELE.jpg',
  "MEUNIER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MEUNIER.jpg',
  "SEYS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SEYS.jpg',
  "CASTAGNE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CASTAGNE.jpg',
  "WITSEL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WITSEL.jpg',
  "DE BRUYNE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DE_BRUYNE.jpg',
  "TIELEMANS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TIELEMANS.jpg',
  "VANAKEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VANAKEN.jpg',
  "SAELEMAEKERS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SAELEMAEKERS.jpg',
  "RASKIN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RASKIN.jpg',
  "ONANA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ONANA.jpg',
  "LUKAKU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LUKAKU.jpg',
  "TROSSARD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TROSSARD.jpg',
  "DOKU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DOKU.jpg',
  "LUKEBAKIO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LUKEBAKIO.jpg',
  "VASILJ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VASILJ.jpg',
  "HADŽIKADUNIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HADZIKADUNIC.jpg',
  "KOLAŠINAC": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOLASINAC.jpg',
  "DEDIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DEDIC.jpg',
  "KATIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KATIC.jpg',
  "MALIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MALIC.jpg',
  "TAHIROVIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TAHIROVIC.jpg',
  "GIGOVIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GIGOVIC.jpg',
  "BAŠIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BASIC.jpg',
  "SUNJIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SUNJIC.jpg',
  "HADŽIAHMETOVIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HADZIAHMETOVIC.jpg',
  "BURNIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BURNIC.jpg',
  "MAHMIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAHMIC.jpg',
  "DŽEKO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DZEKO.jpg',
  "ALAJBEGOVIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ALAJBEGOVIC.jpg',
  "TABAKOVIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TABAKOVIC.jpg',
  "LUKIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LUKIC.jpg',
  "A. BECKER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/A_BECKER.jpg',
  "WEVERTON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WEVERTON.jpg',
  "EDERSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/EDERSON.jpg',
  "GABRIEL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GABRIEL.jpg',
  "MARQUINHOS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MARQUINHOS.jpg',
  "ALEX SANDRO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ALEX_SANDRO.jpg',
  "DANILO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DANILO.jpg',
  "IBAÑEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/IBANEZ.jpg',
  "CASEMIRO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CASEMIRO.jpg',
  "BRUNO G.": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BRUNO_G.jpg',
  "VINI JR.": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VINI_JR.jpg',
  "CUNHA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CUNHA.jpg',
  "NEYMAR JR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NEYMAR_JR.jpg',
  "RAPHINHA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RAPHINHA.jpg',
  "ENDRICK": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ENDRICK.jpg',
  "MARTINELLI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MARTINELLI.jpg',
  "VOZINHA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VOZINHA.jpg',
  "STOPIRA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/STOPIRA.jpg',
  "BORGES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BORGES.jpg',
  "LOPES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LOPES.jpg',
  "COSTA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/COSTA.jpg',
  "MOREIRA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MOREIRA.jpg',
  "KELVIN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KELVIN.jpg',
  "MONTEIRO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MONTEIRO.jpg',
  "RODRIGUES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RODRIGUES.jpg',
  "DA COSTA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DA_COSTA.jpg',
  "BENCHIMOL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BENCHIMOL.jpg',
  "ST. CLAIR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ST_CLAIR.jpg',
  "CRÉPEAU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CREPEAU.jpg',
  "GOODMAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GOODMAN.jpg',
  "JOHNSTON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JOHNSTON.jpg',
  "JONES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JONES.jpg',
  "WATERMAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WATERMAN.jpg',
  "CORNELIUS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CORNELIUS.jpg',
  "BOMBITO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BOMBITO.jpg',
  "DAVIES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DAVIES.jpg',
  "LARYEA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LARYEA.jpg',
  "SIGUR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SIGUR.jpg',
  "CHOINIÈRE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CHOINIERE.jpg',
  "EUSTÁQUIO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/EUSTAQUIO.jpg',
  "KONÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KONE.jpg',
  "MILLAR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MILLAR.jpg',
  "SHAFFELBURG": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SHAFFELBURG.jpg',
  "OSORIO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OSORIO.jpg',
  "SALIBA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SALIBA.jpg',
  "LARIN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LARIN.jpg',
  "J. DAVID": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/J_DAVID.jpg',
  "BUCHANAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BUCHANAN.jpg',
  "PROMISE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PROMISE.jpg',
  "NELSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NELSON.jpg',
  "OSPINA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OSPINA.jpg',
  "D. MUÑOZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/D_MUNOZ.jpg',
  "ARIAS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ARIAS.jpg',
  "PUERTA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PUERTA.jpg',
  "MACHADO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MACHADO.jpg',
  "SÁNCHEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SANCHEZ.jpg',
  "RICHARD RÍOS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RICHARD_RIOS.jpg',
  "CARRASCAL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CARRASCAL.jpg',
  "J. ARIAS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/J_ARIAS.jpg',
  "PORTILLA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PORTILLA.jpg',
  "QUINTERO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/QUINTERO.jpg',
  "SUÁREZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SUAREZ.jpg',
  "MPASI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MPASI.jpg',
  "WAN BISSAKA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WAN_BISSAKA.jpg',
  "TUANZEBE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TUANZEBE.jpg',
  "BATUBINSIKA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BATUBINSIKA.jpg',
  "KALULU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KALULU.jpg',
  "MASUAKU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MASUAKU.jpg',
  "MOUTOUSSAMY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MOUTOUSSAMY.jpg',
  "BONGONDA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BONGONDA.jpg',
  "SADIKI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SADIKI.jpg',
  "TSHIBOLA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TSHIBOLA.jpg',
  "PICKEL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PICKEL.jpg',
  "E. KAYEMBE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/E_KAYEMBE.jpg',
  "BAKAMBU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BAKAMBU.jpg',
  "WISSA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WISSA.jpg',
  "BANZA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BANZA.jpg',
  "Y. FOFANA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/Y_FOFANA.jpg',
  "KONE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KONE.jpg',
  "LAFONT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LAFONT.jpg',
  "O. DIOMANDE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/O_DIOMANDE.jpg',
  "SINGO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SINGO.jpg',
  "KOSSOUNOU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOSSOUNOU.jpg',
  "OPERI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OPERI.jpg',
  "G. DOUE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/G_DOUE.jpg',
  "SERI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SERI.jpg',
  "FOFANA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FOFANA.jpg',
  "KESSIE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KESSIE.jpg',
  "GUIAGON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GUIAGON.jpg',
  "BONNY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BONNY.jpg',
  "ADINGRA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ADINGRA.jpg',
  "YAN DIOMANDE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/YAN_DIOMANDE.jpg',
  "DIAKITE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DIAKITE.jpg',
  "AMAD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AMAD.jpg',
  "PEPE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PEPE.jpg',
  "GUESSAND": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GUESSAND.jpg',
  "LIVAKOVIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LIVAKOVIC.jpg',
  "PANDUR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PANDUR.jpg',
  "KOTARSKI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOTARSKI.jpg',
  "STANIŠIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/STANISIC.jpg',
  "PONGRAČIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PONGRACIC.jpg',
  "GVARDIOL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GVARDIOL.jpg',
  "ĆALETA-CAR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CALETACAR.jpg',
  "ŠUTALO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SUTALO.jpg',
  "JAKIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JAKIC.jpg',
  "ERLIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ERLIC.jpg',
  "MORO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MORO.jpg',
  "KOVAČIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOVACIC.jpg',
  "MODRIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MODRIC.jpg',
  "VLAŠIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VLASIC.jpg',
  "PAŠALIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PASALIC.jpg',
  "BATURINA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BATURINA.jpg',
  "P. SUČIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/P_SUCIC.jpg',
  "SUČIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SUCIC.jpg',
  "KRAMARIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KRAMARIC.jpg',
  "BUDIMIR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BUDIMIR.jpg',
  "PERIŠIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PERISIC.jpg',
  "MATANOVIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MATANOVIC.jpg',
  "M. PAŠALIĆ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/M_PASALIC.jpg',
  "MUSA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MUSA.jpg',
  "GALÍNDEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GALINDEZ.jpg',
  "TORRES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TORRES.jpg',
  "PACHO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PACHO.jpg',
  "VITE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VITE.jpg',
  "M. CAICEDO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/M_CAICEDO.jpg',
  "YEBOAH ZAMORA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/YEBOAH_ZAMORA.jpg',
  "ARÉVALO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AREVALO.jpg',
  "SHOUBIR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SHOUBIR.jpg',
  "R. RABIA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/R_RABIA.jpg',
  "H. HASSAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/H_HASSAN.jpg',
  "MARMOUSH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MARMOUSH.jpg',
  "ZIZO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZIZO.jpg',
  "PICKFORD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PICKFORD.jpg',
  "D. HENDERSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/D_HENDERSON.jpg',
  "TRAFFORD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TRAFFORD.jpg',
  "KONSA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KONSA.jpg',
  "O'REILLY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OREILLY.jpg',
  "STONES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/STONES.jpg',
  "CHALOBAH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CHALOBAH.jpg',
  "BURN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BURN.jpg',
  "QUANSAH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/QUANSAH.jpg',
  "RICE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RICE.jpg',
  "ANDERSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ANDERSON.jpg',
  "BELLINGHAM": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BELLINGHAM.jpg',
  "HENDERSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HENDERSON.jpg',
  "MAINOO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAINOO.jpg',
  "ROGERS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ROGERS.jpg',
  "EZE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/EZE.jpg',
  "SAKA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SAKA.jpg',
  "KANE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KANE.jpg',
  "RASHFORD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RASHFORD.jpg',
  "MADUEKE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MADUEKE.jpg',
  "TONEY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TONEY.jpg',
  "SAMBA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SAMBA.jpg',
  "MAIGNAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAIGNAN.jpg',
  "RISSER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RISSER.jpg',
  "GUSTO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GUSTO.jpg',
  "DIGNE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DIGNE.jpg',
  "UPAMECANO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/UPAMECANO.jpg',
  "KOUNDÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOUNDE.jpg',
  "KONATÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KONATE.jpg',
  "T. HERNANDEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/T_HERNANDEZ.jpg',
  "L. HERNANDEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/L_HERNANDEZ.jpg',
  "LACROIX": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LACROIX.jpg',
  "TCHOUAMENI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TCHOUAMENI.jpg',
  "RABIOT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RABIOT.jpg',
  "ZAIRE-EMERY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZAIREEMERY.jpg',
  "CHERKI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CHERKI.jpg',
  "AKLIOUCHE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AKLIOUCHE.jpg',
  "DEMBÉLÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DEMBELE.jpg',
  "MBAPPÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MBAPPE.jpg',
  "OLISE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OLISE.jpg',
  "BARCOLA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BARCOLA.jpg',
  "DOUÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DOUE.jpg',
  "MATETA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MATETA.jpg',
  "NEUER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NEUER.jpg',
  "BAUMANN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BAUMANN.jpg',
  "NÜBEL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NUBEL.jpg',
  "RÜDIGER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RUDIGER.jpg',
  "ANTON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ANTON.jpg',
  "TAH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TAH.jpg',
  "KIMMICH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KIMMICH.jpg',
  "SCHLOTTERBECK": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SCHLOTTERBECK.jpg',
  "BROWN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BROWN.jpg',
  "RAUM": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RAUM.jpg',
  "THIAW": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/THIAW.jpg',
  "GORETZKA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GORETZKA.jpg',
  "LEWELING": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LEWELING.jpg',
  "MUSIALA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MUSIALA.jpg',
  "STILLER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/STILLER.jpg',
  "WIRTZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WIRTZ.jpg',
  "SANÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SANE.jpg',
  "AMIRI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AMIRI.jpg',
  "NMECHA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NMECHA.jpg',
  "OUÉDRAOGO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OUEDRAOGO.jpg',
  "HAVERTZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HAVERTZ.jpg',
  "WOLTEMADE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WOLTEMADE.jpg',
  "BEIER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BEIER.jpg',
  "UNDAV": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/UNDAV.jpg',
  "ZIGI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZIGI.jpg',
  "ANANG": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ANANG.jpg',
  "B. ASARE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/B_ASARE.jpg',
  "ADJETEY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ADJETEY.jpg',
  "OPOKU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OPOKU.jpg',
  "LUCKASSEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LUCKASSEN.jpg',
  "SENEYA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SENEYA.jpg',
  "YIRENKYI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/YIRENKYI.jpg',
  "PARTEY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PARTEY.jpg',
  "SIBO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SIBO.jpg',
  "SEMENYO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SEMENYO.jpg',
  "OWUSU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OWUSU.jpg',
  "BOAKYE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BOAKYE.jpg',
  "J. AYEW": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/J_AYEW.jpg',
  "WILLIAMS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WILLIAMS.jpg',
  "KAMALDEEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KAMALDEEN.jpg',
  "PRINCE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PRINCE.jpg',
  "SUZUKI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SUZUKI.jpg',
  "OSAKO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OSAKO.jpg',
  "SUGAWARA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SUGAWARA.jpg',
  "TANIGUCHI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TANIGUCHI.jpg',
  "ITAKURA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ITAKURA.jpg',
  "NAGATOMO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NAGATOMO.jpg',
  "WATANABE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WATANABE.jpg',
  "H. ITO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/H_ITO.jpg',
  "TOMIYASU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TOMIYASU.jpg',
  "TANAKA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TANAKA.jpg',
  "KUBO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KUBO.jpg',
  "DOAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DOAN.jpg',
  "DAIZEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DAIZEN.jpg',
  "NAKAMURA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NAKAMURA.jpg',
  "ITO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ITO.jpg',
  "KAMADA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KAMADA.jpg',
  "Y. SUZUKI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/Y_SUZUKI.jpg',
  "SANO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SANO.jpg',
  "MACHINO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MACHINO.jpg',
  "GOTO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GOTO.jpg',
  "AYASE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AYASE.jpg',
  "E. ÁLVAREZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/E_ALVAREZ.jpg',
  "FIDALGO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FIDALGO.jpg',
  "B. GUTIÉRREZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/B_GUTIERREZ.jpg',
  "S. GIMÉNEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/S_GIMENEZ.jpg',
  "G. MARTÍNEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/G_MARTINEZ.jpg',
  "BONO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BONO.jpg',
  "TAGNAOUTI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TAGNAOUTI.jpg',
  "HAKIMI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HAKIMI.jpg',
  "MAZRAOUI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAZRAOUI.jpg',
  "RIAD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RIAD.jpg',
  "BELAMMARI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BELAMMARI.jpg',
  "HALHAL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HALHAL.jpg',
  "SALAH-EDDINE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SALAHEDDINE.jpg',
  "AMRABAT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AMRABAT.jpg',
  "BOUADDI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BOUADDI.jpg',
  "TALBI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TALBI.jpg',
  "OUNAHI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OUNAHI.jpg',
  "SAIBARI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SAIBARI.jpg',
  "YASSINE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/YASSINE.jpg',
  "EL AYNAOUI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/EL_AYNAOUI.jpg',
  "RAHIMI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RAHIMI.jpg',
  "SBAI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SBAI.jpg',
  "EL KAABI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/EL_KAABI.jpg',
  "VERBRUGGEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VERBRUGGEN.jpg',
  "FLEKKEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FLEKKEN.jpg',
  "GEERTRUIDA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GEERTRUIDA.jpg',
  "VIRGIL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VIRGIL.jpg',
  "AKÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AKE.jpg',
  "WIEFFER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WIEFFER.jpg',
  "DUMFRIES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DUMFRIES.jpg',
  "HATO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HATO.jpg',
  "KLUIVERT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KLUIVERT.jpg',
  "GRAVENBERCH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GRAVENBERCH.jpg',
  "REIJNDERS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/REIJNDERS.jpg',
  "TIL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TIL.jpg',
  "KOOPMEINERS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOOPMEINERS.jpg',
  "Q. TIMBER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/Q_TIMBER.jpg',
  "WEGHORST": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WEGHORST.jpg',
  "MEMPHIS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MEMPHIS.jpg',
  "GAKPO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GAKPO.jpg',
  "LANG": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LANG.jpg',
  "MALEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MALEN.jpg',
  "BROBBEY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BROBBEY.jpg',
  "SUMMERVILLE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SUMMERVILLE.jpg',
  "NYLAND": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NYLAND.jpg',
  "TANGVIK": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TANGVIK.jpg',
  "SELVIK": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SELVIK.jpg',
  "VASSBAKK AJER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VASSBAKK_AJER.jpg',
  "ØSTIGÅRD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OSTIGARD.jpg',
  "BJØRKAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BJORKAN.jpg',
  "HOLMGREN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HOLMGREN.jpg',
  "HEGGEM": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HEGGEM.jpg',
  "LANGÅS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LANGAS.jpg',
  "FALCHENER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FALCHENER.jpg',
  "THORSBY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/THORSBY.jpg',
  "BERG": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BERG.jpg',
  "BERGE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BERGE.jpg',
  "ØDEGAARD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ODEGAARD.jpg',
  "AURSNES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AURSNES.jpg',
  "THORSTVEDT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/THORSTVEDT.jpg',
  "AASGAARD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AASGAARD.jpg',
  "SCHJELDERUP": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SCHJELDERUP.jpg',
  "BOBB": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BOBB.jpg',
  "SØRLOTH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SORLOTH.jpg',
  "BRAUT HAALAND": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BRAUT_HAALAND.jpg',
  "STRAND LARSEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/STRAND_LARSEN.jpg',
  "NUSA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NUSA.jpg',
  "RYERSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RYERSON.jpg',
  "VELÁZQUEZ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VELAZQUEZ.jpg',
  "ALDERETE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ALDERETE.jpg',
  "MAURÍCIO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAURICIO.jpg',
  "CUBAS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CUBAS.jpg',
  "GALARZA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GALARZA.jpg',
  "R. GAMARRA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/R_GAMARRA.jpg',
  "PITTA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PITTA.jpg',
  "DIOGO COSTA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DIOGO_COSTA.jpg',
  "JOSÉ SÁ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JOSE_SA.jpg',
  "N. SEMEDO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/N_SEMEDO.jpg',
  "RÚBEN DIAS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RUBEN_DIAS.jpg',
  "DALOT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DALOT.jpg',
  "RENATO VEIGA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RENATO_VEIGA.jpg',
  "JOÃO CANCELO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JOAO_CANCELO.jpg',
  "SAMU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SAMU.jpg',
  "MATHEUS N.": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MATHEUS_N.jpg',
  "JOÃO NEVES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JOAO_NEVES.jpg',
  "VITINHA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/VITINHA.jpg',
  "G. RAMOS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/G_RAMOS.jpg',
  "JOÃO FÉLIX": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JOAO_FELIX.jpg',
  "NETO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NETO.jpg',
  "Y. DIOUF": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/Y_DIOUF.jpg',
  "MENDY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MENDY.jpg',
  "DIAW": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DIAW.jpg',
  "SARR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SARR.jpg',
  "KOULIBALY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOULIBALY.jpg',
  "SECK": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SECK.jpg',
  "JAKOBS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JAKOBS.jpg',
  "DIATTA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DIATTA.jpg',
  "NIAKHATÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NIAKHATE.jpg',
  "GANA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GANA.jpg',
  "P.I. CISS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PI_CISS.jpg',
  "LAMINE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LAMINE.jpg',
  "H. DIARRA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/H_DIARRA.jpg',
  "GUEYE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GUEYE.jpg',
  "A. DIAO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/A_DIAO.jpg',
  "BAMBA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BAMBA.jpg',
  "MANÉ": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MANE.jpg',
  "N. JACKSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/N_JACKSON.jpg',
  "NDIAYE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NDIAYE.jpg',
  "ISMAILA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ISMAILA.jpg',
  "I. MBAYE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/I_MBAYE.jpg',
  "MODIBA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MODIBA.jpg',
  "KABINI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KABINI.jpg',
  "MUDAU": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MUDAU.jpg',
  "MAKHANYA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MAKHANYA.jpg',
  "CROSS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CROSS.jpg',
  "ZWANE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZWANE.jpg',
  "ADAMS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ADAMS.jpg',
  "FOSTER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FOSTER.jpg',
  "MOFOKENG": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MOFOKENG.jpg',
  "MASEKO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MASEKO.jpg',
  "JOAN GARCIA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JOAN_GARCIA.jpg',
  "UNAI SIMON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/UNAI_SIMON.jpg',
  "MARC PUBILL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MARC_PUBILL.jpg',
  "GRIMALDO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GRIMALDO.jpg',
  "ERIC": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ERIC.jpg',
  "M. LLORENTE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/M_LLORENTE.jpg',
  "PEDRO PORRO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PEDRO_PORRO.jpg',
  "CUBARSI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CUBARSI.jpg',
  "CUCURELLA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/CUCURELLA.jpg',
  "MERINO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MERINO.jpg',
  "ALEX B.": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ALEX_B.jpg',
  "RODRIGO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RODRIGO.jpg',
  "ZUBIMENDI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZUBIMENDI.jpg',
  "PEDRI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PEDRI.jpg',
  "FERRAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FERRAN.jpg',
  "OLMO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OLMO.jpg',
  "YEREMY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/YEREMY.jpg',
  "WILLIAMS JR.": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WILLIAMS_JR.jpg',
  "LAMINE YAMAL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LAMINE_YAMAL.jpg',
  "OYARZABAL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OYARZABAL.jpg',
  "B. IGLESIAS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/B_IGLESIAS.jpg',
  "ZETTERSTRÖM": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZETTERSTROM.jpg',
  "NORDFELDT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NORDFELDT.jpg',
  "LINDELÖF": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/LINDELOF.jpg',
  "HIEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/HIEN.jpg',
  "GUDMUNDSSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GUDMUNDSSON.jpg',
  "H. JOHANSSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/H_JOHANSSON.jpg',
  "SVENSSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SVENSSON.jpg',
  "EKDAL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/EKDAL.jpg',
  "STARFELT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/STARFELT.jpg',
  "BERNHARDSSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BERNHARDSSON.jpg',
  "STROUD": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/STROUD.jpg',
  "BERGVALL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BERGVALL.jpg',
  "NYGREN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NYGREN.jpg',
  "SEMA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SEMA.jpg',
  "KARLSTRÖM": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KARLSTROM.jpg',
  "AYARI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AYARI.jpg',
  "SVANBERG": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SVANBERG.jpg',
  "ZENELI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ZENELI.jpg',
  "ISAK": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ISAK.jpg',
  "ELANGA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ELANGA.jpg',
  "GYÖKERES": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/GYOKERES.jpg',
  "ALI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ALI.jpg',
  "KOBEL": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/KOBEL.jpg',
  "MUHEIM": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/MUHEIM.jpg',
  "WIDMER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WIDMER.jpg',
  "ELVEDI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ELVEDI.jpg',
  "AKANJI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AKANJI.jpg',
  "CÖMERT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/COMERT.jpg',
  "FREULER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FREULER.jpg',
  "XHAKA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/XHAKA.jpg',
  "JASHARI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/JASHARI.jpg',
  "EMBOLO": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/EMBOLO.jpg',
  "NDOYE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/NDOYE.jpg',
  "FASSNACHT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FASSNACHT.jpg',
  "OKAFOR": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/OKAFOR.jpg',
  "ITTEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ITTEN.jpg',
  "FREESE": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/FREESE.jpg',
  "DEST": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/DEST.jpg',
  "RICHARDS": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/RICHARDS.jpg',
  "A. ROBINSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/A_ROBINSON.jpg',
  "TRUSTY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TRUSTY.jpg',
  "ARFSTEN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ARFSTEN.jpg',
  "SCALLY": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/SCALLY.jpg',
  "REYNA": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/REYNA.jpg',
  "BERHALTER": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BERHALTER.jpg',
  "ROLDAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/ROLDAN.jpg',
  "TILLMAN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/TILLMAN.jpg',
  "PEPI": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PEPI.jpg',
  "PULISIC": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/PULISIC.jpg',
  "AARONSON": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/AARONSON.jpg',
  "WRIGHT": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WRIGHT.jpg',
  "BALOGUN": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/BALOGUN.jpg',
  "WEAH": 'https://cdn.jsdelivr.net/gh/Rufinorris/bolao-copa-2026@master/fotos/WEAH.jpg',
};

// Lookup síncrono — chave = nome de camisa
function getFoto(nome) {
  if (Object.prototype.hasOwnProperty.call(FOTOS, nome)) return FOTOS[nome];
  try {
    const c = sessionStorage.getItem(`foto_${nome}`);
    if (c !== null) return c === '' ? null : c;
  } catch {}
  return null;
}

// Desabilitado: fallback Wikipedia causava imagens erradas (páginas homônimas)
async function _fetchWikiThumbnail(nome) { return null; }

async function precarregarFotos(nomes) {
  const pendentes = nomes.filter(n => {
    if (Object.prototype.hasOwnProperty.call(FOTOS, n)) return false;
    try { if (sessionStorage.getItem(`foto_${n}`) !== null) return false; } catch {}
    return true;
  });
  await Promise.allSettled(pendentes.map(async (nome) => {
    const url = await _fetchWikiThumbnail(nome);
    try { sessionStorage.setItem(`foto_${nome}`, url || ''); } catch {}
  }));
}
